Outer-Wilds-New-Horizons/new-horizons

NewHorizons/Builder/Props/DialogueBuilder.cs
Probably could find a better time to read the input xml as it is read every time the object is loaded. Similarly it tries to insert into the translation table on load.
=> Custom Dialogue

NewHorizons/Builder/StarSystem/SkyboxBuilder.cs, NewHorizons/External/Configs/StarSystemConfig.cs, NewHorizons/Handlers/SystemCreationHandler.cs, NewHorizons/star_system_schema.json
You can now add custom skyboxes by making a skybox material in Unity and importing it:
(in a star system config)
```json
{
"skybox": {
"assetBundle": "path/to/my/bundle",
"path": "Assets/path/to/my/material.mat"
}
}
```
[skybox.zip](https://github.com/xen-42/outer-wilds-new-horizons/files/8644164/skybox.zip) Here's an example bundle, the path of the material is: `Assets/Materials/Skybox.mat`
=> Added the ability to make custom sky boxes

NewHorizons/Builder/Props/ProjectionBuilder.cs, NewHorizons/Patches/ToolModeSwapperPatches.cs, NewHorizons/Patches/VisionTorchPatches.cs
- in the title: vision torch no longer blocks equipping ship tools 
- ie if you're piloting your ship while holding a vision torch, you can use the scout launcher, signalscope, etc, as expected
- Vision torch targets now support the "on vision complete" event
=> vision torch no longer blocks equipping ship tools

NewHorizons/Builder/Props/DetailBuilder.cs
- In detail builder, added handling for two component types:
- InteractVolume
- PlayerAttachPoint
- This fixes campfires (before they'd create an ever increasing number of input prompts while you looked at them, and also wouldn't let you roast marshmallows), and possibly other props
=> fixes campfires spawned using DetailBuilder

NewHorizons/Handlers/SubtitlesHandler.cs, NewHorizons/Main.cs
If you load a save and then go back to the main menu, the addon subtitles show up as white rectangles:
This bug happens because subtitle textures are destroyed when the `ImageUtilities` cache is cleared, but the static field  `possibleSubtitles` in `SubtitlesHandler` keeps sprites with these textures.
Another bug happens when configs are reloaded, that makes all subtitles to be added again to the list of `possibleSubtitles`, essentialy duplicating them. As a result of this duplication, the "same" subtitle could be selected twice in a row.
To fix these two bugs, textures for subtitles are loaded when the `SubtitlesHandler` is created (this happens when the menu scene loads and `TitleSceneHandler.InitSubtitles` is called) and the `possibleSubtitles`  is no longer a static field.
=> Fix white and duplicated subtitles

NewHorizons/Builder/Props/ProjectionBuilder.cs, NewHorizons/Patches/AutoSlideProjectorPatches.cs
`blackFrameDuration` is supposed to add a black frame of a given duration before showing the real slide (it also blocks the manual projector to change the slide for that duration). However, NH has a bug and after that duration, the real image of the reel isn't displayed. This happens because `SlideBlackFrameModule`  sets the `textureOverride` of the slide to a black texture and then, after the `blackFrameDuration`, to `null`. And NH stores the texture of the reel also in `textureOverride`, so to fix it I made it store in `_image` instead. 
This works because  `textureOverride` takes precedence over `_image` when it isn't `null` (see `Slide.GetTexture()`), meaning that when `SlideBlackFrameModule` sets it to the black texture, the texture of the slide will be black, and then after the …
=> Fix slide not showing after blackFrameDuration

NewHorizons/Utility/DebugMenu/DebugMenuPropPlacer.cs, NewHorizons/Utility/DebugUtilities/DebugPropPlacer.cs
- Added controls to the prop placer menu to adjust the transform of the most recently placed prop, including:
- position
- rotation
- scale
- position in spherical coordinates
- rotation about the local up direction (relative to current local rotation)
- Removed props loaded from configs from the "recently placed props" menu - they were really cluttering up that list
=> Prop placer menu prop positioning controls

NewHorizons/Utility/AstroObjectLocator.cs, NewHorizons/Utility/DebugUtilities/DebugPropPlacer.cs
- made AstroObjectLocator also register astro objects under the name of their game object, eg MyPlanet_Body
- (fixes an issue where prop placer wouldn't save new props placed on custom planets)
=> Fix prop placer for custom planets

NewHorizons/Builder/Body/BrambleDimensionBuilder.cs, NewHorizons/Builder/Props/BrambleNodeBuilder.cs
It does weird stuff when not 1 and shouldn't be used instead of fog density
=> Ignore bramble fog alpha

NewHorizons/Builder/Body/ProxyBuilder.cs, NewHorizons/Builder/Props/DetailBuilder.cs, NewHorizons/Builder/Props/PropBuildManager.cs
Makes detail making stuff just be in a single method call. The `Make` method now just handles getting the prefab, if its from a path or from an asset bundle. No longer inconsistent when using different detail options like parenting, renaming, removing components, etc.
=> Refactor detail builder, fix parenting issue

NewHorizons/Builder/Props/RemoteBuilder.cs, NewHorizons/External/Modules/PropModule.cs, NewHorizons/Schemas/body_schema.json
You can now disable individual parts of projection platforms and shared whiteboards.
For whiteboards you can disable walls
For platforms you can disable the floor structure and the pool that rises when you place a stone.
=> Add options to disable parts of remote props

NewHorizons/Builder/Body/BrambleDimensionBuilder.cs
I think sometimes nodes are built after BrambleSectorController registers renderers, meaning some nodes don't get hidden. This PR attempts to fix that.
=> Make dimensions cull inner nodes

NewHorizons/Utility/SearchUtilities.cs
writes it as a 3-strategy process, since that's effectively what it is. makes it so that not finding the root wont immediately return null
=> improve SearchUtilities.Find

NewHorizons/Main.cs
Added a warning when an empty systems or planets folder is found.
Fixes https://github.com/Outer-Wilds-New-Horizons/new-horizons/issues/353
Should behave identical to current solution for JSON and JSONC files, maybe someone on Windows can test. Worked flawlessly on Linux with Real Solar System, The Vision and Carson System.
=> Fix JSON file lookup for Proton

NewHorizons/Builder/Props/DialogueBuilder.cs, NewHorizons/Handlers/TranslationHandler.cs
-
-
-
- The game trims the text of `Page` and `DialogOption` and this is used in the key that indexes the translation table. However, this trim was missing in NH, causing the game to fail to find the translation (and displaying the key as a fallback). For example, [this](https://github.com/FixxionsLair/Secret-Words/blob/78dd665323d745f88cd4bd531c13f29020233a06/planets/Dialogue/Fixxion.xml#L46) would cause the error `String "1Jötunn is a really cold planet, it's kinda hard to live in and it's so dark but" not found in table for language ENG` because there is an space at the end of the string and the game displays "1Jötunn is a really cold planet, it's kinda hard to live in and it's so dark but" with the "1" at the start.
=> Fix dialog text not trimmed in translation table key

NewHorizons/Builder/Props/ProjectionBuilder.cs, NewHorizons/Utility/ImageUtilities.cs
Makes it handle slides with no path better, properly log errors when it fails to load images, added tracking for if the image is loaded yet or not (unused currently, could disable the slide/vision target if the image don't load?).
=> Vision torch image loading bug

NewHorizons/Builder/Props/ProjectionBuilder.cs, NewHorizons/External/Modules/PropModule.cs, NewHorizons/Schemas/body_schema.json
- Added `playWithShipLogFacts ` to `slideShows` to make reels play in ship log computer.. #389
- Fix NRE errors caused by visions (`visionTorchTarget` and `standingVisionTorch`) initialization. #392
- Fix reels (`slideReel`) showing up in Echoes of the Eye entries replacing the vanilla reel:
=> Implement #389 playWithShipLogFacts, fix #392

NewHorizons/Builder/Atmosphere/VolumesBuilder.cs, NewHorizons/Builder/General/GravityBuilder.cs, NewHorizons/Builder/Volumes/PriorityVolumeBuilder.cs, NewHorizons/Builder/Volumes/VolumesBuildManager.cs, NewHorizons/Builder/Volumes/ZeroGVolumeBuilder.cs, NewHorizons/External/Configs/PlanetConfig.cs, NewHorizons/External/Modules/BaseModule.cs, NewHorizons/External/Modules/VolumesModule.cs, NewHorizons/Schemas/body_schema.json
- `zeroGravityRadius` has been replaced by `zeroGravityVolumes` in the `Volumes` module.
- Can now set the priority of zero g volumes and gravity volumes #292
=> Gravity priority

NewHorizons/Components/ShipLog/ShipLogStarChartMode.cs, NewHorizons/External/NewHorizonsData.cs, NewHorizons/Main.cs
this turns off owml's backslash "fixer"
apparently, the backslash fixer was implemented for path-character reasons. 
unfortunately, it happens to break all escape characters, such as The Vision's https://github.com/Outer-Wilds-New-Horizons/new-horizons/issues/424#issuecomment-1281856989
it being disabled doesn't seem to break anything.
further testing on linux is probably needed. obv i cant do that testing.
=> dont touch backslashes

NewHorizons/Patches/ShipLogPatches.cs
- Fix NH ship log facts of vanilla bodies required for the Archaeologist achievement #428 
It turns out there is already a patch for this, but it was only excluding facts from entries of NH astro bodies but not NH facts of vanilla bodies.
=> fix #428: NH ship log facts are required for the Archaeologist achievement

docs/content/pages/tutorials/translation.md
- Added a CLI Tool section to the Translations page of the documentation.
I created with reference to the Config Editor page. However, I am not a native English speaker, so please let me know if there are any sentences that are grammatically incorrect.
=> docs: add cli tool section

NewHorizons/INewHorizons.cs, NewHorizons/NewHorizonsApi.cs, docs/content/pages/tutorials/api.md, docs/content/pages/tutorials/extending.md
**Untested right now**
Now that OWML supports generic API methods, this PR makes `QueryBody` and `QuerySystem` have generic counterparts.
The generic methods are a bit different from the others, as they'll return `default(T)` if the JSONPath doesn't find anything.
=> Add Generic API Methods

NewHorizons/Builder/Props/DetailBuilder.cs, NewHorizons/Schemas/body_schema.json, NewHorizons/Schemas/star_system_schema.json, NewHorizons/Utility/DebugMenu/DebugMenuNomaiText.cs, NewHorizons/Utility/DebugUtilities/DebugPropPlacer.cs, NewHorizons/Utility/DebugUtilities/DebugRaycastData.cs, NewHorizons/Utility/DebugUtilities/DebugRaycaster.cs, NewHorizons/Utility/MColor.cs, NewHorizons/Utility/NewHorizonExtensions.cs
- Debug Raycast now writes the rotation value to use to have the placed object aligned to the surface its on and facing towards the player.
- `alignToNormal` now no longer breaks on vanilla planets.
=> Detail rotation fix

NewHorizons/Utility/DebugUtilities/DebugRaycaster.cs
makes xen's raycast rotation work in ship and other non-ao bodies, and also just generally cleans up the code a bit.
=> make raycast cleaner

NewHorizons/Builder/ShipLog/RevealBuilder.cs, NewHorizons/External/Modules/VolumesModule.cs, NewHorizons/Schemas/body_schema.json
Can now choose whether the player, scout, or both can trigger the enter reveal volume.
I have not tested this yet.
=> Add "reveal for" option to enter reveal volumes

NewHorizons/Builder/Body/BrambleDimensionBuilder.cs, NewHorizons/External/Modules/BrambleModule.cs, NewHorizons/Schemas/body_schema.json
Replaces `hasVines` with `vinePrefab` so you can use various dimension vines for variety without having to deal with custom vines
=> Add vinePrefab option

NewHorizons/Main.cs, NewHorizons/Patches/TimeLoopPatches.cs
Should fix a few bugs from #407 and more
- Background stars no longer go supernova when time loop is disabled
- Sun no longer does supernova effects while disabled
- Sun will not expand into red giant when time loop is disabled
- Interloper no longer disappears when time loop is disabled
- End times music will not play when time loop is disabled
- Time loop component no longer triggers supernova when time loop is disabled
=> Fix some time loop bugs

NewHorizons/Utility/AssetBundleUtilities.cs
when i fixed it i forgot about dummy shaders (which dont have the proper render queue set)
so this makes it only preserve stuff when the material queue is different from the shader queue (ie we want to preserve that difference)
=> fix shader replacement mistake

NewHorizons/Builder/Props/BrambleNodeBuilder.cs, NewHorizons/External/Modules/BrambleModule.cs, NewHorizons/Schemas/body_schema.json
Option to manually remove a sender warp for cases where the recursion scanner fails.
=> Manual bramble recursion fix

NewHorizons/Builder/Body/WaterBuilder.cs, NewHorizons/External/Modules/VariableSize/WaterModule.cs, NewHorizons/Schemas/body_schema.json
=> Add buoyancy and density properties to water

NewHorizons/Builder/Body/HeightMapBuilder.cs, NewHorizons/Builder/Props/ScatterBuilder.cs
because Newtonsoft.Json makes strings empty by default
=> Make height map builder use string.IsNullOrEmpty instead

NewHorizons/Builder/Props/DialogueBuilder.cs, NewHorizons/External/Modules/PropModule.cs, NewHorizons/Patches/RemoteDialogueTriggerPatches.cs
- Add `remoteTriggerPrereqCondition` to only show a remote dialogue trigger once a condition has been met.
- Stop RemoteDialogueTrigger from softlocking you if you disable its CharacterDialogueTree.
=> More remote dialogue stuff

NewHorizons/Builder/Body/SingularityBuilder.cs, NewHorizons/Builder/Volumes/ChangeStarSystemVolumeBuilder.cs, NewHorizons/Builder/Volumes/CreditsVolumeBuilder.cs, NewHorizons/Builder/Volumes/VolumesBuildManager.cs, NewHorizons/Components/Volumes/BlackHoleWarpVolume.cs, NewHorizons/Components/Volumes/LoadCreditsVolume.cs, NewHorizons/Components/Volumes/WarpVolume.cs, NewHorizons/External/Modules/VolumesModule.cs, NewHorizons/Schemas/body_schema.json, NewHorizons/manifest.json
- Added `solarSystemVolume` and `creditsVolume` to the `Volumes` module. Lets you change star system without setting up a black hole, and allows going straight to the fast, final, or kazoo credits scenes.
=> Add volumes for changing star system and triggering credits

NewHorizons/Builder/Body/WaterBuilder.cs, NewHorizons/Builder/Props/DetailBuilder.cs, NewHorizons/Builder/Volumes/HazardVolumeBuilder.cs
- Ghost matter from detail props and from HazardVolumes now should be deactivated when going underwater.
=> Submerge dark matter

NewHorizons/Builder/Props/DetailBuilder.cs
set a field instead of calling a method because Awake hasnt run yet
=> Fix submerge controller PR

NewHorizons/Builder/Props/BrambleNodeBuilder.cs, NewHorizons/Patches/BramblePatches.cs, NewHorizons/manifest.json
Instead of always patching false, use the ratio between exit radius and warp radius to determine if it's a seed.
=> Fix fog fading occurring for bramble seeds

NewHorizons/Builder/Props/TranslatorText/TranslatorTextBuilder.cs, NewHorizons/External/Modules/PropModule.cs, NewHorizons/Schemas/body_schema.json
- Added a `whiteboard` type to `translatorText` props. If `xmlFile` is set, it will spawn with a scroll already inserted with that text.
- Slightly better error logging if `xmlFile` is not provided for translator text props that require it
=> Translator Text Whiteboard With Scroll

NewHorizons/Builder/Body/SingularityBuilder.cs, NewHorizons/Handlers/PlanetCreationHandler.cs, NewHorizons/Main.cs
- Deferred singularity linking until after all planets are built, so build order no longer affects pairs where only one has `pairedSingularity` set.
=> Defer singularity linking

NewHorizons/Builder/Props/DetailBuilder.cs, NewHorizons/Builder/Props/TranslatorText/TranslatorTextBuilder.cs, NewHorizons/Builder/Props/WarpPadBuilder.cs, NewHorizons/External/Modules/PropModule.cs, NewHorizons/External/Modules/WarpPad/NomaiWarpTransmitterInfo.cs, NewHorizons/Schemas/body_schema.json
also 
- remove ignoresun on details
- fix cairn nre
- remove groups from keeploaded details
- make unused field in warp transmitter info used
=> better version of remove keepautoplacement

NewHorizons/Builder/Props/NomaiTextBuilder.cs, NewHorizons/Builder/Props/TranslatorText/TranslatorTextBuilder.cs, NewHorizons/External/Modules/Props/TranslatorText/NomaiTextArcInfo.cs, NewHorizons/Schemas/body_schema.json
Adds a new arc type to translator text. This is a mix between child and adult. It uses the adult mesh but the child texture.
Originally used at the window text on Giant's Deep's statue island.
=> Add teenager arc type

NewHorizons/Builder/General/AmbientLightBuilder.cs, NewHorizons/Handlers/VesselCoordinatePromptHandler.cs, NewHorizons/Utility/Files/ImageUtilities.cs
-
-
- generated textures are now cached. this should reduce memory usage
- textures are named by file path and then the effects applied to them, for example `[path] > invert > tint [color]`
-
fix #581
=> basic generated texture cache

NewHorizons/Patches/EchoesOfTheEyePatches/DreamworldControllerPatches.cs
- Fixed fog in DLC location (had broken the Hazy Dreams addon) (Thanks Vio!)
=> Vio fixed Dreamworld fog

NewHorizons/Builder/Props/DialogueBuilder.cs, NewHorizons/External/Modules/Props/Dialogue/DialogueInfo.cs, NewHorizons/Patches/DialoguePatches/HearthianRecorderEffectsPatches.cs, NewHorizons/Schemas/body_schema.json
- Can now use `pathToAnimController` on a character dialogue to link it to a Hearthian recorder so that it's visual effects will be triggered during the dialogue #520
=> Allow using pathToAnimController for recorders #520

NewHorizons/Builder/Props/WarpPadBuilder.cs, NewHorizons/Components/NomaiWarpTransmitterCooldown.cs
- Added a 5 second delay to warp transmitters after you come back through the return pad. Means 360 degree alignment target actually works when returning through it instead of sending you straight back. (resolves #563)
=> Adds a 5 second cooldown to warp transmitters after using return pad

NewHorizons/External/Configs/AddonConfig.cs, NewHorizons/Main.cs, NewHorizons/OtherMods/MenuFramework/MenuHandler.cs, NewHorizons/Schemas/addon_manifest_schema.json
- Starting popups can be shown multiple times using `repeatPopup` in the addon-manifest file #621
=> Add repeatPopup field to addon-manifest

NewHorizons/Builder/General/SpawnPointBuilder.cs, NewHorizons/External/Modules/SpawnModule.cs, NewHorizons/Handlers/PlanetDestructionHandler.cs, NewHorizons/Handlers/PlayerSpawnHandler.cs
- Added `offset` to player and ship spawn positions. By default it moves them up by 4m to prevent clipping into the ground but this can be non ideal in cramped spawn locations.
=> Spawn offset

NewHorizons/Builder/General/SpawnPointBuilder.cs, NewHorizons/Builder/Props/DetailBuilder.cs, NewHorizons/Components/Props/ConditionalObjectActivation.cs, NewHorizons/External/Modules/Props/DetailInfo.cs, NewHorizons/Schemas/body_schema.json
-
- Added `activationCondition` and `deactivationCondition` to details, allowing them to be enabled/disabled depending on a dialogue condition. Resolves #482.
- If the `path` for a detail is empty it will create an empty game object now. This can be useful for adding other props to it as its children.
-
=> Hide on condition

NewHorizons/Builder/Atmosphere/CloudsBuilder.cs, NewHorizons/Builder/Atmosphere/VolumesBuilder.cs, NewHorizons/Builder/Props/Audio/SignalBuilder.cs, NewHorizons/Builder/Props/PropBuildManager.cs, NewHorizons/Builder/Props/TornadoBuilder.cs, NewHorizons/Builder/Volumes/HazardVolumeBuilder.cs, NewHorizons/Components/NHProxy.cs, NewHorizons/Components/SizeControllers/StarEvolutionController.cs, NewHorizons/Components/Stars/StellarDeathController.cs, NewHorizons/Components/Stars/SunLightEffectsController.cs, NewHorizons/External/Modules/Props/TornadoInfo.cs, NewHorizons/Handlers/PlanetCreationHandler.cs, NewHorizons/Patches/GlobalMusicControllerPatches.cs, NewHorizons/Schemas/body_schema.json
- Allow setting hazard type and damage per second, as well as first contact damage, for tornados and hurricanes. Resolves #496 
- Throw errors when attempting to make a signal without a frequency or name. Resolves #660.
- Supernovae are no longer silent. Fixes #522.
- Supernovae proxies will no longer explode on top of you.
- Lightning now appears properly on top of basic clouds. Fixes #321.
- Bramble music won't play if in another audio volume. Fixes #651.
- Fix QM clouds defaulting to GD fog when not given a tint. Fixes #182.
=> Killer tornados + various fixes

NewHorizons/Builder/General/SpawnPointBuilder.cs, NewHorizons/Components/Ship/ShipWarpController.cs, NewHorizons/Handlers/PlayerSpawnHandler.cs
-
-
-
- Fixes ship being broken when spawning on the center of the universe. Resolves #648
=> Fix spawn on center of universe garbage

NewHorizons/Builder/General/RigidBodyBuilder.cs, NewHorizons/Builder/Orbital/OrbitlineBuilder.cs, NewHorizons/External/Modules/BaseModule.cs, NewHorizons/Handlers/PlanetCreationHandler.cs, NewHorizons/Main.cs, NewHorizons/Schemas/body_schema.json
- `AddPhysics` on `Base` module for planets allows a planet to be pushed out of orbit. Intended for satellites or small props floating in orbit. Implements #194
- Fix default system override being unreliable #687
=> AddPhysics on planet allows it to be deorbited #194

NewHorizons/Builder/Body/StarBuilder.cs, NewHorizons/Builder/Props/DetailBuilder.cs, NewHorizons/Patches/SolarFlareEmitterPatches.cs, NewHorizons/manifest.json
- Fix flares turning white in the main system again #668
- Fix rotations of props that used `RemoveComponents`. This won't visibly affect any existing mods, and just makes it so that the rotation shown in Unity Explorer will match what's used in the config.
=> Fix flares being white #668

NewHorizons/Builder/Body/StellarRemnantBuilder.cs, NewHorizons/External/Configs/PlanetConfig.cs, NewHorizons/External/Modules/VariableSize/StarModule.cs, NewHorizons/Schemas/body_schema.json, SchemaExporter/SchemaExporter.cs
- Pulsar's are obsolete now because NH is done. Backwards compat will leave them as neutron stars.
=> Obsolete pulsars

NewHorizons/Builder/Props/BrambleNodeBuilder.cs
- Fixed a bug where fog preview lights were being affected too much by node scaling (cause of #574)
- Fixed an issue where fog of bramble nodes was being double scaled (maybe caused by c9ee5ec1ac38a7ad9b5b9c4c7329ec526bf8cace)
I included a planet folder that adds a little node orbiting DB. That node should be able to demonstrate the old & new behaviors.
[planets.zip](https://github.com/Outer-Wilds-New-Horizons/new-horizons/files/12629245/planets.zip)
=> Bramble Fixes

NewHorizons/Builder/Atmosphere/EffectsBuilder.cs, NewHorizons/Builder/Props/DetailBuilder.cs, NewHorizons/Main.cs, NewHorizons/Utility/DebugTools/DebugReload.cs
-
-
- Ghost animator components don't always get removed now (except when they need to be)
- fix bug where ParticleFields assumes you have an Atmosphere and fails to build your planet if you dont
- Reload configs always reload bundles now
=> allow ghosts to work in bundles maybe

NewHorizons/Builder/Body/BrambleDimensionBuilder.cs, NewHorizons/Builder/Props/DetailBuilder.cs, NewHorizons/Builder/Props/GravityCannonBuilder.cs, NewHorizons/Builder/Props/ItemBuilder.cs, NewHorizons/Builder/Props/NomaiTextBuilder.cs, NewHorizons/Builder/Props/ProjectionBuilder.cs, NewHorizons/Builder/Props/PropBuildManager.cs, NewHorizons/Builder/Props/RemoteBuilder.cs, NewHorizons/Builder/Props/ScatterBuilder.cs, NewHorizons/Builder/Props/ShuttleBuilder.cs, NewHorizons/Builder/Props/TranslatorText/TranslatorTextBuilder.cs, NewHorizons/Builder/Props/WarpPadBuilder.cs, NewHorizons/Components/Props/NHItem.cs, NewHorizons/Components/Props/NHItemSocket.cs, NewHorizons/External/Modules/Props/DetailInfo.cs, NewHorizons/External/Modules/Props/Item/ItemInfo.cs, NewHorizons/External/Modules/Props/Item/ItemSocketInfo.cs, NewHorizons/Handlers/PlanetCreationHandler.cs, NewHorizons/Handlers/PlanetDestructionHandler.cs, NewHorizons/INewHorizons.cs, NewHorizons/Main.cs, NewHorizons/NewHorizonsApi.cs, NewHorizons/Schemas/body_schema.json, NewHorizons/Utility/DebugTools/DebugPropPlacer.cs
- Custom items and item sockets, as an extension of the existing details. Interactivity can be added without code by setting dialogue conditions with an item's `pickupCondition` or socket's `insertCondition`, and then turning other details on or off using their `activationCondition`.
- Added API methods for looking up translated strings for localization.
=> Item and Item Socket Props

NewHorizons/Handlers/SystemCreationHandler.cs, NewHorizons/OtherMods/OtherModUtil.cs, NewHorizons/Utility/OuterWilds/TimeLoopUtilities.cs
- StopTime and SlowTime mods will now effect the time loop in new systems
=> Implement StopTime, SlowTime mod compat

NewHorizons/Builder/Props/BrambleNodeBuilder.cs
- Fixed an issue where Bramble-propagated signals would have a detection area.
[planets.zip](https://github.com/Outer-Wilds-New-Horizons/new-horizons/files/13880774/planets.zip)
The attached file puts a bramble node near the Hearthian Village that demonstrates the different behaviors.
=> Stop propagated signals from having a detection area

NewHorizons/Patches/ShipLogPatches/ShipLogManagerPatches.cs
- Exhibitions in the museum on the Eye correctly reflects shiplog
- By avoiding to make shiplog empty when arriving at the eye as in solarsystem.
=> Exhibitions in the museum on the Eye correctly reflects shiplog

NewHorizons/Components/Volumes/StreamingWarpVolume.cs
Context is a guy reported the Codec black hole lagging their game, I imagine it could be because of this but I couldn't reproduce it and have no idea what would cause any of these things to be null.
- Fix possible lag when near black holes
=> Check for null refs inside streaming warp volume then destroy it

NewHorizons/Builder/Props/DetailBuilder.cs, NewHorizons/Builder/Props/ItemBuilder.cs, NewHorizons/External/Modules/Props/Item/ItemInfo.cs, NewHorizons/Schemas/body_schema.json
- Added `colliderRadius` to custom items. All custom items will be given a collider for cursor/hover detection unless this is set to 0.
- Fixed some edge cases in collision detection with custom items.
=> Add sphere collider to custom items

NewHorizons/Builder/Props/DetailBuilder.cs, NewHorizons/External/Modules/Props/DetailInfo.cs, NewHorizons/Schemas/body_schema.json, NewHorizons/Utility/Files/ImageUtilities.cs
- sector cull groups now function properly (not erroneously enabled even without keeploaded) (fix #792)
- fixes a problem where projected slides are brighter than the source image (fix #755)
=> Fix SectorCullGroup on details

NewHorizons/Builder/Props/ItemBuilder.cs, NewHorizons/Components/Props/NHItem.cs, NewHorizons/External/Modules/Props/Item/ItemInfo.cs, NewHorizons/Schemas/body_schema.json
- Added `holdOffset`, `holdRotation`, `socketOffset`, and `socketRotation` to control the positioning of custom items when held or socketed (implements #821).
=> Position and rotation offsets for custom item holding and socketing

NewHorizons/Builder/Props/DetailBuilder.cs, NewHorizons/Builder/Props/DialogueBuilder.cs, NewHorizons/Components/Fixers/PlayerShipAtmosphereDetectorFix.cs, NewHorizons/Handlers/TranslationHandler.cs, NewHorizons/Utility/NewHorizonExtensions.cs, NewHorizons/manifest.json
- To avoid having to copy paste a repeated `DialogueOptionsList`, you can instead put `ReuseDialogueOptionsListFrom` and reference another `DialogueNode` whose options you want to repeat. Implements #854
=> ReuseDialogueOptionsListFrom

NewHorizons/Schemas/dialogue_schema.xsd, NewHorizons/Schemas/shiplog_schema.xsd, NewHorizons/Schemas/text_schema.xsd
- Added ReuseDialogueOptionsListFrom, DisablePersistentCondition, and ParentIgnoreNotRevealed to their respective schemas
- Specify (and also correct some) minOccurs & maxOccurs on EVERYTHING (this one is for you visual studio)
- Rearranged things to better match the xmls from vanilla
=> Fix and update xsd schemas

NewHorizons/Patches/DialoguePatches/CharacterDialogueTreePatches.cs
- fix #859: CharacterDialogueTree.InConversation is now checked in our attachment patch to avoid unnecessary EndConversation calls.
=> Check InConversation to avoid unnecessary EndConversation calls

NewHorizons/Builder/Props/PropBuildManager.cs, NewHorizons/Builder/Props/ScatterBuilder.cs, NewHorizons/External/Modules/Props/ScatterInfo.cs, NewHorizons/Schemas/body_schema.json
- Added `parentPath` to scatter. This parent should be at the position where you'd like to scatter (which would usually be zero).
- Fix scatter not working properly on tidally locked bodies
=> Scatter parenting and fixes for tidally locked bodies

NewHorizons/Handlers/PlanetCreationHandler.cs
- Fixed returning to solar system radius not being calculated correctly
=> Fix the solar system radius calculation

NewHorizons/Builder/Props/DialogueBuilder.cs
- If `pathToExistingDialogue` points to a dialogue object that has a null asset, it will now set its asset to yours instead of erroring.
- We now search in the body for `pathToExistingDialogue`. You no longer have to put the root object at the beginning of the path.
=> Allow adding an xml to an existing dialogue that had a null asset

NewHorizons/Assets/newhorizons_private.manifest, NewHorizons/Builder/Props/ProjectionBuilder.cs, NewHorizons/External/Modules/Props/EchoesOfTheEye/ProjectionInfo.cs, NewHorizons/External/Modules/Props/EchoesOfTheEye/SlideInfo.cs, NewHorizons/Schemas/body_schema.json
- New `reelModel` and `reelCondition` parameters in prop `slideShows` for slide reel mesh and material. (#811)
- Models: 6-slided, 7-slided, 8-slided, and Whole (7-slided but connected like 8-slided).
- Conditions: Antique (Stranger), Pristine (Dreamworld), Rusted (Burnt)
- `rotate` parameter added to slide info. Rotates the slide reel item while inside a projector.
=> Add different slide reel prefabs

NewHorizons/Builder/ShipLog/MapModeBuilder.cs, NewHorizons/Handlers/PlanetCreationHandler.cs
- Map mode icon setting changes now work when updating an existing planet. Fixes #875
=> Allow replacing ship log map mode icons of existing planets

NewHorizons/Builder/Props/DetailBuilder.cs, NewHorizons/Handlers/EyeDetailCacher.cs, NewHorizons/Main.cs, NewHorizons/Utility/DebugTools/DebugReload.cs, NewHorizons/Utility/OuterWilds/AstroObjectLocator.cs, NewHorizons/Utility/SearchUtilities.cs
- When making changes to the Eye of the Universe you can now use any path from the base solar system. Note some objects might not behave as expected since many things aren't made to exist at the eye.
=> Cache details used on the eye

NewHorizons/Patches/LocatorPatches.cs, NewHorizons/Patches/SignalPatches/AudioSignalPatches.cs
- Fix inactive signals being used with signalscope strongest signal method. This bug prevented some vanilla frequencies from showing up in custom systems.
=> Fix inactive signals being used with signalscope strongest signal method

NewHorizons/Main.cs, NewHorizons/NewHorizonsApi.cs, docs/src/content/docs/guides/extending-configs.md
- Added log message in the event the QueryBody could not find a body
- Fixed documentation to match API
- Discovered that if you modify the default SolarySystem, `QuerySystem` will fail due to an IO error as the relative path is not set. While not an ideal solution, we have settled on just setting the relativePath if a mod adjusts the system. This will mean that the last mod loaded that makes these changes will have set the relative path.
=> Fix documentation error and add log for future debuging for QueryBody; Set SolarSystem relative path if a mod adds a .json file to overwrite it.

NewHorizons/Builder/Props/DialogueBuilder.cs, NewHorizons/External/Modules/Props/Dialogue/AttentionPointInfo.cs, NewHorizons/External/Modules/Props/Dialogue/DialogueInfo.cs, NewHorizons/Schemas/body_schema.json
- Added `attentionPoint` and `swappedAttentionPoints` to dialogue props to allow for controlling what the camera looks at when advancing dialogue. Closes #904 (Requested by @MegaPiggy)
=> Add support for dialogue attention points

NewHorizons/Components/ShipLog/ShipLogStarChartMode.cs, NewHorizons/External/Configs/StarSystemConfig.cs, NewHorizons/External/NewHorizonsSystem.cs, NewHorizons/Handlers/StarChartHandler.cs, NewHorizons/Schemas/star_system_schema.json, NewHorizons/manifest.json
- Added `canExitViaWarpDrive` and `factRequiredToExitViaWarpDrive` to enable/disable warping out of your own system. Replaces setting `canEnterViaWarpDrive = false` on the base solar system (which now does nothing). Fixes compatibility between Astral Codec and anything that uses the warp drive.
=> Can warp home

NewHorizons/Patches/SignalPatches/SignalscopeReticleControllerPatches.cs
- "Orphaned" signalscope reticles are disabled instead of being stuck on screen when a signal is disabled (fixes #925 )
=> Add postfix patch to disable orphaned signalscope reticles (Fixes #925)

NewHorizons/Builder/Atmosphere/AirBuilder.cs, NewHorizons/Builder/Atmosphere/CloudsBuilder.cs, NewHorizons/Builder/Body/ProxyBuilder.cs, NewHorizons/Builder/Body/WaterBuilder.cs, NewHorizons/Builder/General/AstroObjectBuilder.cs, NewHorizons/Builder/General/DetectorBuilder.cs, NewHorizons/Builder/General/SpawnPointBuilder.cs, NewHorizons/Builder/Props/DetailBuilder.cs, NewHorizons/External/Configs/AddonConfig.cs, NewHorizons/External/Configs/PlanetConfig.cs, NewHorizons/External/Modules/AtmosphereModule.cs, NewHorizons/External/Modules/BaseModule.cs, NewHorizons/External/Modules/Props/DetailInfo.cs, NewHorizons/External/Modules/VariableSize/WaterModule.cs, NewHorizons/Handlers/PlanetCreationHandler.cs, NewHorizons/Handlers/SubtitlesHandler.cs, NewHorizons/Schemas/addon_manifest_schema.json, NewHorizons/Schemas/body_schema.json, NewHorizons/Schemas/shiplog_schema.xsd, NewHorizons/manifest.json
-
- Added `allowShipAutoroll` to `Water` and `Atmosphere` (fixes #935)
- Replaced `invulnerableToSun` with `hasFluidDetector` and better documented anglerfish making planets go gorp #830
- Allows subtitles of any size now (images get rescaled if need be) (fixes #893)
- Added documentation of naming scheme for alt ship log images (fixes #848)
- Fix subtitles start cycling before main menu is visible (fixes #844)
- Fix disappearing signalscope UI after warping to new star system (fixes #934)
- Fix null primary body not defaulting to center of universe in other star systems (fixes #933) (probably)
- Fix proxy details requiring "keepLoaded" set to true to work (fixes #940)
- Handle proxy body edge case when all scales = 0 (fixes #941)
=> Multiple fixes

NewHorizons/Builder/Body/SingularityBuilder.cs, NewHorizons/Builder/General/SpawnPointBuilder.cs, NewHorizons/Builder/Volumes/ChangeStarSystemVolumeBuilder.cs, NewHorizons/Components/ShipLog/ShipLogStarChartMode.cs, NewHorizons/Components/Volumes/BlackHoleWarpVolume.cs, NewHorizons/Components/Volumes/WarpVolume.cs, NewHorizons/External/Configs/PlanetConfig.cs, NewHorizons/External/Modules/SpawnModule.cs, NewHorizons/External/Modules/VariableSize/SingularityModule.cs, NewHorizons/External/Modules/Volumes/VolumeInfos/ChangeStarSystemVolumeInfo.cs, NewHorizons/External/NewHorizonBody.cs, NewHorizons/External/NewHorizonsSystem.cs, NewHorizons/Handlers/PlanetCreationHandler.cs, NewHorizons/Handlers/PlayerSpawnHandler.cs, NewHorizons/Handlers/ShipLogHandler.cs, NewHorizons/Handlers/StarChartHandler.cs, NewHorizons/Handlers/VesselWarpHandler.cs, NewHorizons/INewHorizons.cs, NewHorizons/Main.cs, NewHorizons/NewHorizonsApi.cs, NewHorizons/manifest.json
- The spawn module now has `playerSpawnPoints` and `shipSpawnPoints` allowing you to define multiple possible spawns on one planet.
- Spawn points now have `makeDefaultIfFactRevealed` and `makeDefaultIfPersistentCondition` allowing you to change which spawn the player uses. Priority goes fact -> persistent condition -> default
- Black holes and change star system volumes now have `spawnPointID`. If this is set, entering one of these volumes will send you to the spawn with a matching `id` (fixes #917)
- Fix empty warp drive ship log page appearing
- Use save data directly when checking for facts for ship log warp drive
=> Multiple spawn points

NewHorizons/Handlers/HeldItemHandler.cs, NewHorizons/Handlers/PlayerSpawnHandler.cs, NewHorizons/Main.cs, NewHorizons/Patches/TimeLoopPatches.cs
- Preserve held items when warping (closes #192). Note that if you leave an item in another system and warp out, that item will be gone forever from all systems until you start a new loop. Some items (i.e., slide reels) do not work between systems.
- Time loop will be disabled in other systems if you removed the AWC and warped while holding it or using the Vessel. Closes #952
=> Held item tracking

NewHorizons/Builder/Props/DetailBuilder.cs, NewHorizons/Builder/Props/EchoesOfTheEye/AlarmTotemBuilder.cs, NewHorizons/Builder/Props/EchoesOfTheEye/DreamCandleBuilder.cs, NewHorizons/Builder/Props/EchoesOfTheEye/GrappleTotemBuilder.cs, NewHorizons/Builder/Props/EchoesOfTheEye/PortholeBuilder.cs, NewHorizons/Builder/Props/EchoesOfTheEye/ProjectionTotemBuilder.cs, NewHorizons/Builder/Props/PropBuildManager.cs, NewHorizons/External/Modules/PropModule.cs, NewHorizons/External/Modules/Props/EchoesOfTheEye/AlarmTotemInfo.cs, NewHorizons/External/Modules/Props/EchoesOfTheEye/DreamCandleInfo.cs, NewHorizons/External/Modules/Props/EchoesOfTheEye/DreamCandleType.cs, NewHorizons/External/Modules/Props/EchoesOfTheEye/GrappleTotemInfo.cs, NewHorizons/External/Modules/Props/EchoesOfTheEye/PortholeInfo.cs, NewHorizons/External/Modules/Props/EchoesOfTheEye/ProjectionTotemInfo.cs, NewHorizons/Patches/EchoesOfTheEyePatches/AlarmTotemPatches.cs, NewHorizons/Patches/EchoesOfTheEyePatches/DreamworldControllerPatches.cs, NewHorizons/Patches/EchoesOfTheEyePatches/LanternZoomPointPatches.cs, NewHorizons/Patches/EchoesOfTheEyePatches/PeepholePatches.cs, NewHorizons/Schemas/body_schema.json
- New dream world related prop types: alarm totems, grapple totems, projection totems, portholes/peepholes, and dream candles. Where possible, these have been modified to work with the regular flashlight as well as the artifact for use outside of the dream world.
=> New Dream World Props

NewHorizons/Builder/ShipLog/RumorModeBuilder.cs, NewHorizons/Patches/ShipLogPatches/ShipLogManagerPatches.cs, docs/src/content/docs/guides/ship-log.md
- Modded ship log entries with the same ID as an existing entry are now merged into that original entry, allowing for new rumor and explore facts and sub-entries to be added to vanilla ship log entries. Implements #996
=> Shiplog Entry Merging

NewHorizons/Builder/Body/AsteroidBeltBuilder.cs, NewHorizons/Builder/Body/HeightMapBuilder.cs, NewHorizons/External/Modules/AsteroidBeltModule.cs, NewHorizons/Schemas/body_schema.json
- Added an option to use a detail for asteroid belts, instead of just procgen.
- Also added asteroid belt options for gravity and random orientation.
- Fixed the proxy shadow caster on heightmaps, so they cast shadows onto other bodies better (fixes #1001)
=> fix the heightmap proxy caster guy and also asteroid belt now

NewHorizons/Builder/ShipLog/MapModeBuilder.cs, NewHorizons/External/Modules/ShipLogModule.cs, NewHorizons/Patches/ShipLogPatches/ShipLogAstroObjectPatches.cs, NewHorizons/Patches/ShipLogPatches/ShipLogMapModePatches.cs, NewHorizons/Schemas/body_schema.json
- Added `selectable` to map mode info, allowing you to make the map mode icon not able to be selected (useful for bodies without ship logs like stars) Fixes #1003
=> Add selectable to map mode, fix an NRE, make auto map gen lines debug

NewHorizons/Assets/translations/portuguese_br.json
- Translation for the Portuguese (Brazil) language based on current English translation file.
I tried to keep game's actual context translations by extracting its actual pt_BR file and checking translation choices made throughout the game.
Hope this little contribution is welcome.
=> Populates the portuguese_br.xml translation file.

NewHorizons/Builder/Props/ProjectionBuilder.cs, NewHorizons/Components/EOTE/NHSlideCollection.cs, NewHorizons/Components/EOTE/NHSlideCollectionContainer.cs, NewHorizons/External/Modules/Props/EchoesOfTheEye/ProjectionInfo.cs, NewHorizons/Patches/ShipLogPatches/ShipLogSlideReelPatches.cs, NewHorizons/Patches/ToolPatches/ToolModeSwapperPatches.cs, NewHorizons/Schemas/body_schema.json, NewHorizons/Utility/Files/ImageUtilities.cs, NewHorizons/Utility/Files/SlideReelAsyncImageLoader.cs
- Can set `displaySlides` on a slide reel now to define which slide indices should be displayed on the physical reel model. Fixes #888.
- Slide reels are now streamed (Fixes #898). Other projectors (auto, torch) are not streamed  yet.
- Empty slide reel slots are now transparent on the slide reel model. Requires existing slide reel caches to be cleared.
- Fixed a 3 frame hitch when changing tools
So the strategy is:
If the cache does not exist, do nothing different. It will take like 5 minutes and all your memory but that doesn't matter that's on the dev to make sure that they pre-gen the caches (the sequential pre-caching option should stop you running out of memory when making the cache probably). Users won't experience any of that
Then we just do not ever load the inverted cached …
=> Slide reel streaming

docs/src/content/docs/guides/dialogue.md, docs/src/content/docs/guides/nomai-text.md, docs/src/content/docs/guides/publishing.md
Improved dialogue documentation by writing some more guides (Fixes #833)
I checked through the dialogue and nomai text schemas and I don't see anything missing when compared to base game code.
=> Reorganize a bit and add more docs

NewHorizons/External/Modules/Props/EyeOfTheUniverse/EyeTravelerInfo.cs, NewHorizons/Handlers/EyeSceneHandler.cs, NewHorizons/Schemas/body_schema.json
- Add `afterTraveler` to custom Eye Travelers to place them after a base game traveler in the campfire order (resolves #1037)
- Fix order of travelers at the Eye when both base game guests have been gathered and custom travelers are used
=> Eye Travel Ordering

NewHorizons/Builder/Props/DetailBuilder.cs, NewHorizons/Builder/Props/ItemBuilder.cs, NewHorizons/Components/Conditionals/ConditionalsManager.cs, NewHorizons/Components/Props/NHItem.cs, NewHorizons/External/Configs/StarSystemConfig.cs, NewHorizons/External/Modules/Conditionals/ConditionalCheckInfo.cs, NewHorizons/External/Modules/Props/Item/ItemInfo.cs, NewHorizons/Handlers/ConditionalsHandler.cs, NewHorizons/Handlers/SystemCreationHandler.cs, NewHorizons/Patches/PlayerPatches/PlayerDataPatches.cs, NewHorizons/Schemas/body_schema.json, NewHorizons/Schemas/star_system_schema.json
- Added `conditionalChecks` to star system configs. These allow you to automatically set or unset dialogue conditions, persistent conditions, and ship log facts based on other conditions being met, to handle more complex interactive situations that a single `requiredCondition` or `requiredFact` can't cover. Implements #1048 
- Fixed custom items breaking if `pickupAudio` and `dropAudio` were not set. Custom items will now default to the warp core item sounds. Each sound can be disabled individually by specifying "None" as the audio type.
- Fixed custom items breaking if `removeComponents` was set on the detail.
=> Conditional Checks

NewHorizons/Builder/Props/ItemBuilder.cs, NewHorizons/Builder/Props/NomaiTextBuilder.cs, NewHorizons/Builder/Props/TranslatorText/TranslatorTextBuilder.cs, NewHorizons/External/Modules/Props/Item/ItemInfo.cs, NewHorizons/External/Modules/Props/Item/ItemSocketInfo.cs, NewHorizons/Schemas/body_schema.json
- The sphere colliders added to custom items and item sockets to make them interactible no longer have collision by default. Mod authors can restore the previous behavior by setting `colliderIsTrigger` to false. Resolves #1054.
- Nomai scrolls created using `translatorTexts` no longer have collision. This matches how scrolls behave in the base game.
=> Item Collider Fixes

NewHorizons/Builder/General/GroupsBuilder.cs, NewHorizons/Builder/Props/DetailBuilder.cs, NewHorizons/Handlers/EyeSceneHandler.cs, NewHorizons/Patches/EchoesOfTheEyePatches/SingleLightSensorPatches.cs
- Fixed details not having collision if they were immediately deactivated after being created (for instance, via `activationCondition`)
- Fixed light sensors disabling themselves on activation if their detail was immediately deactivated after being created
=> Fixes for Immediately Disabled Details

NewHorizons/Builder/Body/BrambleDimensionBuilder.cs, NewHorizons/Builder/Props/BrambleNodeBuilder.cs, NewHorizons/Main.cs, NewHorizons/Utility/DebugTools/DebugFogWarp.cs, NewHorizons/default-config.json
- Added a debug option for visualizing the names of custom bramble warp volumes and their entrances/exits. Resolves #1066
=> Add debug bramble name labels

.github/workflows/build.yaml
Build workflow uses a non-existent action to check changed files. Switched it out for a simple call to `git`.
We'll need to:
1. Merge this to `main` so version PRs are updated correctly
2. Merge `main` to `dev` so feature PRs are updated
3. Every other branch should try to merge this in from `dev`
=> Fix Build Workflow

NewHorizons/Builder/Props/DetailBuilder.cs
- Make docks not vanish when the dam breaks (maybe, needs testing)
=> Destroy flood sensors on docks

NewHorizons/Builder/Atmosphere/AtmosphereBuilder.cs, NewHorizons/Builder/Props/EchoesOfTheEye/RaftBuilder.cs, NewHorizons/Builder/Props/EchoesOfTheEye/RaftDockBuilder.cs, NewHorizons/Builder/Props/PropBuildManager.cs, NewHorizons/Builder/Volumes/SpeedLimiterVolumeBuilder.cs, NewHorizons/Builder/Volumes/VolumesBuildManager.cs, NewHorizons/Components/Volumes/SpeedLimiterVolume.cs, NewHorizons/External/Modules/PropModule.cs, NewHorizons/External/Modules/Props/EchoesOfTheEye/RaftDockInfo.cs, NewHorizons/External/Modules/Props/EchoesOfTheEye/RaftInfo.cs, NewHorizons/External/Modules/Volumes/VolumeInfos/SpeedLimiterVolumeInfo.cs, NewHorizons/External/Modules/Volumes/VolumesModule.cs, NewHorizons/Main.cs, NewHorizons/Patches/EchoesOfTheEyePatches/RaftControllerPatches.cs, NewHorizons/Schemas/body_schema.json, NewHorizons/Utility/NewHorizonExtensions.cs
- Added `raftDocks` to `Props` module. An easier way to spawn in docks for rafts.
- Added `dockPath` to `RaftInfo`.  This is a path to the dock the raft will start attached to.
- Added `pristine` boolean to `RaftInfo`.  Makes the raft use the dreamworld model.
- Added `speedLimiterVolumes` to `Volumes` module. This is the same thing the Stranger uses to slow you down.
- NH-made rafts no longer skip a node when riding on the Dam's raft carrier.
=> Docked/Clean Rafts and Speed Limiter Volumes

NewHorizons/Builder/Props/ShapeBuilder.cs, NewHorizons/Builder/Volumes/VolumeBuilder.cs, NewHorizons/External/Modules/Props/ShapeInfo.cs, NewHorizons/Schemas/body_schema.json, NewHorizons/manifest.json
- Change volumes back to using shapes by default (not colliders) else they get disabled when put on held items
- Fixed bug where volume radius gets ignored if you define a sphere shape
=> Fix held item volumes

NewHorizons/Builder/Props/BrambleNodeBuilder.cs, NewHorizons/Builder/Volumes/VanishVolumeBuilder.cs, NewHorizons/Builder/Volumes/VolumeBuilder.cs, NewHorizons/External/Modules/Volumes/VolumeInfos/VanishVolumeInfo.cs, NewHorizons/manifest.json
- Fixed a bug where Vanish/DestructionVolumes no longer worked (they were trying to use sphere shapes when they can only use sphere colliders)
=> Make VanishVolumes never use shapes

NewHorizons/Handlers/PlanetCreationHandler.cs
- do not load unnecessary bundles in custom systems. saves VRAM. does not affect RAM
details stay visible
does not seem to cause softlocks.
works when going from custom to regular (you dont fall thru TH)
seems to cause no extra errors in logs
=> unloading streaming stuff in custom systems

NewHorizons/Builder/Props/ScatterBuilder.cs
What currently happens is that if `preventOverlap` is not true then there is no array of point emptied progressively and points are rolled in a loop of size count for each prop. The problem is that the loop can be infinite due to `i--; // Try this point again`. A reroll happens when `height < propInfo.minHeight` or `height > propInfo.maxHeight`, height being rolled between `heightMap.minHeight` and `heightMap.maxHeight` (which are not the constraints above).
- This PR checks before the loop if there is less than 0.1% chance for the upcoming heightMap rolls to be considered correct, and if not it always skips this check, ignoring `propInfo.minHeight` and `.maxHeight` to prevent a very long (possibly infinite) loop.
=> Add a security check to ScatterBuilder
