NewHorizons/Builder/General/HeavenlyBodyBuilder.cs
NewHorizons/Main.cs

- Fixed some NPE issues.
- Have a method for restoring default planet configuration

Fix an NPE error

---

.gitignore
NewHorizons/Builder/General/ShipLogBuilder.cs
NewHorizons/Builder/Props/PropBuildManager.cs
NewHorizons/Builder/Props/SignalBuilder.cs
NewHorizons/Components/ShipLogDetail.cs
NewHorizons/External/IPlanetConfig.cs
NewHorizons/External/PlanetConfig.cs
NewHorizons/External/PropModule.cs
NewHorizons/External/ShipLogModule.cs
NewHorizons/External/SignalModule.cs
NewHorizons/Main.cs
NewHorizons/NewHorizons.csproj.user
NewHorizons/Tools/Patches.cs
NewHorizons/Utility/MVector2.cs
NewHorizons/Utility/SearchUtilities.cs
NewHorizons/dialogue_schema.xsd
NewHorizons/schema.json
NewHorizons/shiplog_schema.xsd

Added the ability to make custom ship log entries, facts, and map astro-objects.
[Basic Example Planets](https://github.com/xen-42/outer-wilds-new-horizons/files/8010700/planets.zip)

Add Custom Ship Logs

---

NewHorizons/Builder/ShipLog/MapModeBuilder.cs
NewHorizons/Builder/ShipLog/RumorModeBuilder.cs
NewHorizons/Components/ShipLogDetail.cs
NewHorizons/External/ShipLogModule.cs
NewHorizons/Handlers/ShipLogHandler.cs
NewHorizons/Tools/ShipLogPatches.cs
NewHorizons/schema.json
NewHorizons/shiplog_schema.xsd

- Added Manual Positioning in Map Mode
- Added Child Entries
- Added Ability to Override Existing Planets In Map Mode
- Added Grey Scale if Planet is Rumored but not Explored
- Added Alt Text and Images
- Fixed Completion Achievement
- Fixed `initialReveal` and `curiosities` not working in `SolarSystem`
- Organized Ship Log Schema

Improved Ship Log

---

NewHorizons/dialogue_schema.xsd
NewHorizons/schema.json
NewHorizons/shiplog_schema.xsd

- Refactored Body Schema To Use `$ref` and `$defs`
- Made Ship Log Schema Use Pascal Case
- Organized Dialogue Schema

Updated Schemas

---

NewHorizons/Main.cs
NewHorizons/Utility/Logger.cs
NewHorizons/default-config.json

- Logs will now only print if their severity is greater than or equal to the `LogLevel`  setting
- Added a Debug setting
- Added a Reload Configs button in the pause menu that reloads all configs (only appears if Debug is true)

Added Options For Debugging

---

NewHorizons/schema.json

- Changed "color" to "colour" (dang Canadians)
- Fixed an error with `$ref`

Fixed spelling of colour in schema.json

---

NewHorizons/Main.cs
NewHorizons/Utility/DebugRaycaster.cs
NewHorizons/Utility/SearchUtilities.cs

- Debug raycast now only works if `Debug` is true
- Debug raycast now also shows the path of the GameObject
- Fixed asset bundles not reloading
resolves #43 
resolves #42

Fixed Reloading and Debug Raycast

---

NewHorizons/Builder/ShipLog/MapModeBuilder.cs
NewHorizons/External/NewHorizonsData.cs
NewHorizons/Handlers/ShipLogHandler.cs
NewHorizons/Tools/Patches.cs
NewHorizons/Tools/ShipLogPatches.cs

Fixed some ship log bugs

---

NewHorizons/dialogue_schema.xsd

Added condition elements and some other tweaks

Added to Dialogue schema

---

NewHorizons/Builder/Orbital/OrbitlineBuilder.cs
NewHorizons/External/OrbitModule.cs
NewHorizons/schema.json

I added a property that would make the orbit line look like the Hearthian Map Satellite's dotted orbit line.

Dotted Orbit Line

---

NewHorizons/Builder/Body/CloakBuilder.cs
NewHorizons/Builder/Body/Geometry/CubeSphere.cs
NewHorizons/Builder/Body/HeightMapBuilder.cs
NewHorizons/External/HeightMapModule.cs
NewHorizons/Handlers/PlanetCreationHandler.cs
NewHorizons/text_schema.xsd
README.md
docs/Pipfile.lock
docs/config.json
docs/content/pages/home.md

Fix Stretch & Cloak

---

NewHorizons/dialogue_schema.xsd

Document <Randomize/>

---

.gitignore
docs/content/pages/home.md
docs/content/pages/tutorials/details.md

- Added docs for the prop placer

Feat/Prop Placer Docs

---

.github/ISSUE_TEMPLATE/bug_report.yml
README.md

It's just my second account that I forgot to log out of because I dum dum

Remove GrayFix from README

---

NewHorizons/Builder/Body/CloakBuilder.cs
NewHorizons/Components/ShipWarpController.cs
NewHorizons/manifest.json

- Fixed Ship Going Haywire in `Start()`
- Fixed Cloaks not Working in Custom Star Systems

Version 1.2.4

---

NewHorizons/manifest.json

A lot of updates yay
- Fixed slides not showing after blackFrameDuration (thanks Damián/dgarroDC)

Version 1.2.5

---

NewHorizons/Builder/Body/CloakBuilder.cs
NewHorizons/Builder/Props/SignalBuilder.cs
NewHorizons/Handlers/SystemCreationHandler.cs

Fixes the problem where the travel music would not work sometimes.

Audio File Changes

---

NewHorizons/Assets/translations/english.json

Vessel Achievement Text

---

NewHorizons/Handlers/VesselWarpHandler.cs
NewHorizons/Main.cs

For some reason when warping back to the vanilla solar system the screen gets stuck on loading screen.
I fixed it by not setting spawn point for db vessel and just letting the debug warp handle it.

Dark Bramble Vessel Fixes

---

NewHorizons/Builder/Props/DetailBuilder.cs
NewHorizons/Handlers/PlanetCreationHandler.cs
NewHorizons/Utility/AstroObjectLocator.cs
NewHorizons/Utility/DebugMenu/DebugMenuPropPlacer.cs
NewHorizons/Utility/DebugUtilities/DebugPropPlacer.cs

- Undid changes to AstroObjectLocator from last PR
- Fixed prop placer for custom planets again, this time in a different way

Fix prop placer again

---

NewHorizons/Handlers/VesselCoordinatePromptHandler.cs

Dynamic Vessel Coordinate Texture Generation
- Fill out stub for generating new eye coordinate images

Dynamic vessel coordinate texture generation

---

NewHorizons/AchievementsPlus/AchievementHandler.cs
NewHorizons/Builder/Props/DialogueBuilder.cs
NewHorizons/Builder/Props/NomaiTextBuilder.cs
NewHorizons/INewHorizons.cs
NewHorizons/Main.cs
NewHorizons/NewHorizonsApi.cs
NewHorizons/VoiceActing/IVoiceMod.cs
NewHorizons/VoiceActing/VoiceHandler.cs

- Added support for [Voice mod](https://github.com/Krevace/ow-voice-mod). Create a folder called "VoiceMod" in your root mod directory and you can add voice lines for any custom dialogue you've created.

Voice acting

---

NewHorizons/Builder/Props/GeyserBuilder.cs
NewHorizons/External/Modules/PropModule.cs
NewHorizons/Schemas/body_schema.json

- Geysers can be manually offset, and will start at the spout instead of the shaft by default now

Geyser offset

---

NewHorizons/Builder/Body/BrambleDimensionBuilder.cs
NewHorizons/Builder/Props/BrambleNodeBuilder.cs

Fixes allowedEntrances and possibleExits

Fix bramble exits

---

NewHorizons/Builder/Body/StarBuilder.cs
NewHorizons/Components/SizeControllers/StarEvolutionController.cs
NewHorizons/External/Modules/VariableSize/StarModule.cs
NewHorizons/Main.cs
NewHorizons/Schemas/body_schema.json

I hate pull requests
Star lifespans are fully implemented.

Star lifespan fixes

---

NewHorizons/Builder/Props/BrambleNodeBuilder.cs
NewHorizons/External/Modules/BrambleModule.cs
NewHorizons/Schemas/body_schema.json

Set glow shader properties, and also corrected dimension fog default

Fix bramble glow scaling

---

NewHorizons/External/Modules/PropModule.cs
NewHorizons/Schemas/body_schema.json

Change default type to upwards instead of downards

Fix default tornado type

---

NewHorizons/Builder/Props/NomaiTextBuilder.cs

Animated nomai recorders

---

NewHorizons/Builder/Body/StarBuilder.cs
NewHorizons/Components/SizeControllers/StarEvolutionController.cs
NewHorizons/External/Modules/VariableSize/StarModule.cs
NewHorizons/Main.cs
NewHorizons/Schemas/body_schema.json

Stars changes 2

---

NewHorizons/Assets/addon-manifest.json
NewHorizons/External/Configs/AddonConfig.cs
NewHorizons/Handlers/CreditsHandler.cs
NewHorizons/Main.cs
NewHorizons/Patches/CreditsScene/CreditsEntryPatches.cs
NewHorizons/Patches/CreditsScene/CreditsPatches.cs
NewHorizons/Schemas/addon_manifest_schema.json

Implements #246 .
Adds in scrolling credits support from a `credits` list written into the addon-manifest.

Custom credits #246

---

NewHorizons/Builder/Atmosphere/CloudsBuilder.cs
NewHorizons/External/Modules/AtmosphereModule.cs
NewHorizons/Schemas/body_schema.json

It should be 0 like giant's deep

Change default cloud rotation speed

---

docs/content/pages/reference/audio_enum.md

Fix AudioClips in references

---

NewHorizons/Assets/addon-manifest.json
NewHorizons/Patches/VisionTorchPatches.cs

Fix vision torch

---

NewHorizons/Builder/General/AmbientLightBuilder.cs

- Copy from qm instead of bh
- Set inner radius to surface size

Ambient light tweaks

---

NewHorizons/Builder/General/DetectorBuilder.cs
NewHorizons/Handlers/PlanetCreationHandler.cs

Add detectors to static bodies, just don't detect anything #217

---

NewHorizons/Builder/Atmosphere/AtmosphereBuilder.cs
NewHorizons/Builder/Atmosphere/CloudsBuilder.cs
NewHorizons/Builder/Atmosphere/EffectsBuilder.cs
NewHorizons/Builder/Atmosphere/FogBuilder.cs
NewHorizons/Builder/Body/AsteroidBeltBuilder.cs
NewHorizons/Builder/Body/GeometryBuilder.cs
NewHorizons/Builder/Body/HeightMapBuilder.cs
NewHorizons/Builder/Body/LavaBuilder.cs
NewHorizons/Builder/Body/ProcGenBuilder.cs
NewHorizons/Builder/Body/ProxyBuilder.cs
NewHorizons/Builder/Body/SingularityBuilder.cs
NewHorizons/Builder/Body/StarBuilder.cs
NewHorizons/Builder/Body/SupernovaEffectBuilder.cs
NewHorizons/Builder/General/AmbientLightBuilder.cs
NewHorizons/Builder/General/DetectorBuilder.cs
NewHorizons/Builder/Props/TornadoBuilder.cs
NewHorizons/Components/NHProxy.cs
NewHorizons/Components/NHSupernovaPlanetEffectController.cs
NewHorizons/Components/SizeControllers/StarEvolutionController.cs
NewHorizons/Components/TimeLoopController.cs
NewHorizons/External/Modules/BaseModule.cs
NewHorizons/Handlers/PlanetCreationHandler.cs
NewHorizons/Handlers/SupernovaEffectHandler.cs
NewHorizons/Main.cs
NewHorizons/Patches/LocatorPatches.cs
NewHorizons/Patches/ProxyBodyPatches.cs
NewHorizons/Schemas/body_schema.json
NewHorizons/Utility/AstroObjectLocator.cs
NewHorizons/Utility/MColor.cs

Supernova Planet Effect, Proxy Atmosphere, Proxy Fog, Proxy Lightning, and etc.

---

NewHorizons/Builder/Props/VolcanoBuilder.cs

Fix meteor collisions

---

NewHorizons/Assets/translations/english.json
NewHorizons/Assets/translations/french.json
NewHorizons/Builder/Props/SignalBuilder.cs
NewHorizons/Components/Achievement/AchievementObserveTrigger.cs
NewHorizons/Components/Achievement/AchievementSnapshotTrigger.cs
NewHorizons/Components/Achievement/AchievementVolume.cs
NewHorizons/Components/BlackHoleDestructionVolume.cs
NewHorizons/Components/ShipLogStarChartMode.cs
NewHorizons/External/Configs/AddonConfig.cs
NewHorizons/Handlers/PlanetCreationHandler.cs
NewHorizons/Handlers/TranslationHandler.cs
NewHorizons/Main.cs
NewHorizons/OtherMods/AchievementsPlus/AchievementHandler.cs
NewHorizons/OtherMods/AchievementsPlus/AchievementInfo.cs
NewHorizons/OtherMods/AchievementsPlus/IAchievements.cs
NewHorizons/OtherMods/AchievementsPlus/NH/EatenOutsideBrambleAchievement.cs
NewHorizons/OtherMods/AchievementsPlus/NH/MultipleSystemAchievement.cs
NewHorizons/OtherMods/AchievementsPlus/NH/NewFrequencyAchievement.cs
NewHorizons/OtherMods/AchievementsPlus/NH/ProbeLostAchievement.cs
NewHorizons/OtherMods/AchievementsPlus/NH/VesselWarpAchievement.cs
NewHorizons/OtherMods/AchievementsPlus/NH/WarpDriveAchievement.cs
NewHorizons/OtherMods/OWRichPresence/IRichPresenceAPI.cs
NewHorizons/OtherMods/OWRichPresence/RichPresenceHandler.cs
NewHorizons/OtherMods/VoiceActing/IVoiceMod.cs
NewHorizons/OtherMods/VoiceActing/VoiceHandler.cs
NewHorizons/Patches/PlayerDataPatches.cs
NewHorizons/Patches/ShipLogPatches.cs

Adds support for OWRichPresence by MegaPiggy

OW Rich Presence

---

NewHorizons/Builder/Orbital/InitialMotionBuilder.cs
NewHorizons/Handlers/PlanetCreationHandler.cs

Fix eccentric binaries

---

NewHorizons/Handlers/PlanetCreationHandler.cs

Make remove children go last and on any body

---

NewHorizons/External/Configs/StarSystemConfig.cs
NewHorizons/Handlers/VesselCoordinatePromptHandler.cs
NewHorizons/Schemas/star_system_schema.json

Vessel warp prompt fact

---

NewHorizons/Builder/Props/ProjectionBuilder.cs
NewHorizons/Components/SizeControllers/StarEvolutionController.cs
NewHorizons/NewHorizons.csproj
SchemaExporter/SchemaExporter.csproj

- Supernova fixes
- Stop eotu breaking because there is no sun controller
- Use correct prisoner path for vision torch target
- Update packages to latest version

Random Stuff

---

.github/workflows/release_build.yml

Make Release Run When Labeled

---

NewHorizons/Utility/DebugMenu/DebugMenu.cs

Now it actually backups the previous file instead of new file

Better backup

---

NewHorizons/Patches/ShapePatches.cs

I tried a lot of ways to do this but only this one worked so here you go I guess.

Resize volume layers

---

NewHorizons/Builder/Atmosphere/EffectsBuilder.cs

Consider heightmap and sea level for where to cut off rain/snow instead of just surface size.

Make rain/snow heights more robust

---

NewHorizons/OtherMods/OWRichPresence/RichPresenceHandler.cs

So that TRAPPIST-1 will work with rich presence

No - for image key

---

NewHorizons/Builder/Props/NotificationVolumeBuilder.cs
NewHorizons/Builder/Props/PropBuildManager.cs
NewHorizons/Builder/ShipLog/RevealBuilder.cs
NewHorizons/Builder/Volumes/AudioVolumeBuilder.cs
NewHorizons/Builder/Volumes/HazardVolumeBuilder.cs
NewHorizons/Builder/Volumes/NotificationVolumeBuilder.cs
NewHorizons/Builder/Volumes/VolumesBuildManager.cs
NewHorizons/Components/NotificationVolume.cs
NewHorizons/External/Configs/PlanetConfig.cs
NewHorizons/External/Modules/PropModule.cs
NewHorizons/External/Modules/VolumesModule.cs
NewHorizons/Handlers/PlanetCreationHandler.cs
NewHorizons/Schemas/body_schema.json

Add notification and hazard volumes + reorganize volumes

---

NewHorizons/Builder/Atmosphere/CloudsBuilder.cs

Use standard shader for basic clouds

---

NewHorizons/Utility/SearchUtilities.cs

dont include prefabs in search or else distant proxies break horribly

fix find again

---

NewHorizons/Builder/Props/NomaiTextBuilder.cs
NewHorizons/Patches/ShipLogPatches.cs

- forgor to instantiate inactive trailmarker
- Don't do funny entry name prepend for modded facts

Small fixes

---

NewHorizons/Builder/General/SpawnPointBuilder.cs

Suit warp bug

---

NewHorizons/Builder/ShipLog/RevealBuilder.cs
NewHorizons/Builder/Volumes/AudioVolumeBuilder.cs
NewHorizons/Builder/Volumes/HazardVolumeBuilder.cs
NewHorizons/Builder/Volumes/MapRestrictionVolumeBuilder.cs
NewHorizons/Builder/Volumes/NotificationVolumeBuilder.cs
NewHorizons/Builder/Volumes/VolumeBuilder.cs
NewHorizons/Builder/Volumes/VolumesBuildManager.cs
NewHorizons/Components/BaseVolume.cs
NewHorizons/Components/InterferenceVolume.cs
NewHorizons/Components/MapRestrictionVolume.cs
NewHorizons/Components/NotificationVolume.cs
NewHorizons/External/Modules/VolumesModule.cs
NewHorizons/Handlers/InterferenceHandler.cs
NewHorizons/Main.cs
NewHorizons/Patches/HUDPatches.cs
NewHorizons/Schemas/body_schema.json

Add more volumes

---

NewHorizons/Patches/CharacterDialogueTreePatches.cs

- Fix a vanilla bug where being in a conversation and then getting attached to something traps you in dialogue.

End conversation on attach

---

NewHorizons/Builder/Body/ProxyBuilder.cs
NewHorizons/Builder/Body/RingBuilder.cs
NewHorizons/External/Configs/PlanetConfig.cs
NewHorizons/External/Modules/RingModule.cs
NewHorizons/Handlers/PlanetCreationHandler.cs
NewHorizons/Handlers/TitleSceneHandler.cs
NewHorizons/Schemas/body_schema.json

Allow creation of more than one ring

---

NewHorizons/Handlers/CreditsHandler.cs

fix credits (from eye pr lol)

---

NewHorizons/External/Configs/StarSystemConfig.cs
NewHorizons/Patches/MapControllerPatches.cs
NewHorizons/Patches/OWCameraPatch.cs
NewHorizons/Schemas/star_system_schema.json

- Can override the far clip plane for a system from the star system config (you're welcome Jammer)

Allow overriding far clip plane

---

NewHorizons/Builder/Props/ProjectionBuilder.cs

- This fixes race conditions when incrementing `displaySlidesLoaded` becaise `++` isn't thread safe. In the case of `MakeSlideReel`, another issue was fixed that happens even without parallelism: `if (displaySlidesLoaded >= textures.Length)` would always be true after some point and multiple reel textures would be created.  But with parallelism, it's possible for `displaySlidesLoaded` to never reach `textures.Length` and in this case the texture wouldn't be created (or the vision torch enabled). Sadly this doesn't change behavior for vision targets, so this is unrelated to #381

Fix race conditions with slide textures loading

---

NewHorizons/OtherMods/CommonCameraUtility/CommonCameraHandler.cs
NewHorizons/OtherMods/CommonCameraUtility/ICommonCameraAPI.cs
NewHorizons/Patches/CameraPatches/NomaiRemoteCameraPatches.cs
NewHorizons/Patches/CameraPatches/OWCameraPatch.cs
NewHorizons/manifest.json

- Nomai remote cameras (projection pools) display the right camera layers, and better show the protagonist. Uses [CommonCameraUtility](https://github.com/xen-42/ow-common-camera-util)

Common camera utility

---

NewHorizons/Builder/Body/StarBuilder.cs
NewHorizons/Components/SizeControllers/StarEvolutionController.cs
NewHorizons/Components/StarLightController.cs
NewHorizons/Handlers/PlanetCreationHandler.cs
NewHorizons/Handlers/PlanetDestructionHandler.cs

Disable starlights when out of range

---

NewHorizons/Builder/Body/StarBuilder.cs
NewHorizons/Components/SizeControllers/StarEvolutionController.cs
NewHorizons/Components/StarLightController.cs
NewHorizons/Handlers/PlanetCreationHandler.cs
NewHorizons/Handlers/PlanetDestructionHandler.cs

Reverts Outer-Wilds-New-Horizons/new-horizons#345

Revert "Disable starlights when out of range"

---

NewHorizons/Handlers/CreditsHandler.cs

Use section title instead of "Custom" for credits

---

NewHorizons/Builder/Volumes/AudioVolumeBuilder.cs
NewHorizons/External/Modules/VolumesModule.cs
NewHorizons/Schemas/body_schema.json

Volume setting for audio volumes

Audio volume setting

---

NewHorizons/Builder/Props/DetailBuilder.cs
NewHorizons/External/Modules/PropModule.cs
NewHorizons/Schemas/body_schema.json

Detail stretch

---

NewHorizons/Builder/Props/ScatterBuilder.cs
NewHorizons/External/Modules/PropModule.cs
NewHorizons/Schemas/body_schema.json

just copy the way details do it

stretch for scatter too

---

NewHorizons/Builder/Props/DetailBuilder.cs

i removed its usage by accident when reverting the goofy DetailFixer hack xen did LOL!!!!

actually use group builder

---

NewHorizons/Builder/Props/DetailBuilder.cs
NewHorizons/Builder/Props/NomaiTextBuilder.cs
NewHorizons/Utility/DebugUtilities/DebugRaycaster.cs
NewHorizons/Utility/NewHorizonBody.cs
NewHorizons/Utility/SearchUtilities.cs

- Fix components flagged to be removed throwing errors on Awake
- Hardcoded backwards compat for mods broken by keepLoaded = false like WARIO
- Fixed two debug raycast prompts appearing
- Sorted Nomai text prefabs to (hopefully) stop future updates breaking them again (you have to re-orient them still since patch 13, sorry)

Random fixes

---

NewHorizons/Assets/addon-manifest.json
NewHorizons/Builder/ShipLog/RumorModeBuilder.cs
NewHorizons/Main.cs

self explanatory (use it more)

more path.combine

---

NewHorizons/Main.cs
NewHorizons/NewHorizons.csproj
NewHorizons/manifest.json

- Allow translating popups and credits
- Updated OWML version, removed HarmonyX reference (handled by OWML)

Translate credits, popups, update OWML version

---

NewHorizons/Builder/Props/SignalBuilder.cs
NewHorizons/Patches/AudioSignalPatches.cs

- Improved signal scope lag somewhat

Check contains half as much

---

NewHorizons/Components/ShipLog/ShipLogStarChartMode.cs
NewHorizons/Handlers/StarChartHandler.cs
NewHorizons/OtherMods/CustomShipLogModes/CustomShipLogModesHandler.cs
NewHorizons/OtherMods/CustomShipLogModes/ICustomShipLogModes.cs
NewHorizons/Patches/WarpDrivePatches.cs
NewHorizons/manifest.json

- Use the new [Custom Ship Log Modes](https://github.com/dgarroDC/CustomShipLogModes) utility mod to add the Interstellar Mode for better compatibility and functionality with other mods adding modes.
- Fixed Interstellar Mode not selectable when Rumor Mode was disabled by the user
The mod isn't in the database yet (https://github.com/ow-mods/ow-mod-db/pull/445) so don't merge this PR yet!

Use Custom Ship Log Modes utility mod

---

NewHorizons/Builder/Props/ProjectionBuilder.cs

i broke damian thing so now i fix

kid named finger

---

NewHorizons/Builder/Props/DetailBuilder.cs

- Should fix sector issues with details that are placed on multiple planets

Include sector in the key for detail cache

---

docs/content/pages/tutorials/translation.md

- Just a few additional explanations.

docs: add a little explanation

---

NewHorizons/Utility/AssetBundleUtilities.cs

-
-
-
- makes Standard shader transparent materials work in bundles

fix shader replacer

---

NewHorizons/Builder/Body/LavaBuilder.cs
NewHorizons/Builder/Body/SingularityBuilder.cs
NewHorizons/Components/SizeControllers/LavaSizeController.cs

Scale all the shader stuff so it looks the same throughout its scale curve, also fix singularity mistake

Fix lava scaling

---

NewHorizons/Assets/newhorizons_private.manifest
NewHorizons/Builder/Body/BrambleDimensionBuilder.cs
NewHorizons/External/Modules/BrambleModule.cs
NewHorizons/Handlers/VesselWarpHandler.cs
NewHorizons/Main.cs
NewHorizons/Schemas/body_schema.json

Option to remove default vines using bundle for unbatched collider

Bramble vine removal

---

NewHorizons/Builder/Props/NomaiTextBuilder.cs
NewHorizons/External/Modules/PropModule.cs
NewHorizons/Schemas/body_schema.json

Add timber hearth cairn variant

---

NewHorizons/Builder/Body/BrambleDimensionBuilder.cs

Makes dimensions check if they encounter themselves by scanning outwards from nodes that lead to them.

Prevent bramble recursion from causing hard crash

---

NewHorizons/Builder/Props/BrambleNodeBuilder.cs

Use config name for bramble nodes

Use config name for bramble nodes

---

NewHorizons/Handlers/StreamingHandler.cs
NewHorizons/Utility/AudioUtilities.cs
NewHorizons/manifest.json

- make streaming handler only load thing in if the player or probe enters the sector
- better error reporting in AudioUtilities

a few minor fixes

---

NewHorizons/Builder/Props/BrambleNodeBuilder.cs
NewHorizons/Builder/Props/NomaiTextBuilder.cs
NewHorizons/Handlers/StreamingHandler.cs
NewHorizons/Patches/StreamingPatches.cs

- leaving sectors now unloads streamed things

streaming unloading

---

NewHorizons/Builder/Props/DialogueBuilder.cs
NewHorizons/Builder/Props/SignalBuilder.cs
NewHorizons/External/Modules/PropModule.cs
NewHorizons/Schemas/body_schema.json

- `pathToAnimController` now works for `TravelerController` and `TravelerEyeController`. Means entering dialogue can stop them playing their instruments, change their animation, and make them look at you.

Traveler anim fixes

---

NewHorizons/Builder/Body/SingularityBuilder.cs
NewHorizons/Builder/Props/DetailBuilder.cs
NewHorizons/Builder/Props/DialogueBuilder.cs
NewHorizons/Builder/Props/GeyserBuilder.cs
NewHorizons/Builder/Props/NomaiTextBuilder.cs
NewHorizons/Builder/Props/ProjectionBuilder.cs
NewHorizons/Builder/Props/RaftBuilder.cs
NewHorizons/Builder/Props/RemoteBuilder.cs
NewHorizons/Builder/Props/SignalBuilder.cs
NewHorizons/Builder/Props/VolcanoBuilder.cs
NewHorizons/Builder/ShipLog/EntryLocationBuilder.cs
NewHorizons/Builder/ShipLog/RevealBuilder.cs
NewHorizons/Builder/Volumes/HazardVolumeBuilder.cs
NewHorizons/Builder/Volumes/NotificationVolumeBuilder.cs
NewHorizons/Builder/Volumes/VanishVolumeBuilder.cs
NewHorizons/Builder/Volumes/VolumeBuilder.cs

- Log more errors if a `parentPath` is set improperly

Change parent path warning log to error + add missing

---

NewHorizons/Handlers/PlanetCreationHandler.cs
NewHorizons/Patches/AudioSignalPatches.cs
NewHorizons/Utility/ImageUtilities.cs

- Fix most OWRigidobjects not following a planet when it's moved.
- Fix slide projections being low-res on lower graphics settings. (#303)

Fix some bugs

---

NewHorizons/External/Configs/StarSystemConfig.cs
NewHorizons/Main.cs
NewHorizons/Schemas/star_system_schema.json

Add respawn here option

---

NewHorizons/Assets/translations/chinese_simple.json

Simplified Chinese translation completed

Add Simplified Chinese translation

---

NewHorizons/Builder/Body/WaterBuilder.cs
NewHorizons/Builder/Props/DetailBuilder.cs
NewHorizons/Builder/Volumes/HazardVolumeBuilder.cs
NewHorizons/Components/SizeControllers/WaterSizeController.cs
NewHorizons/manifest.json

-
-
-
- make ghost matter hazard volume builder workee

fix submerge controller again

---

NewHorizons/Utility/Cache.cs

-
-
- Empty caches are no longer written to disk
-

no writing empty caches

---

NewHorizons/Utility/Cache.cs

-
- 
- don't write unchanged caches
-

don't write unmodified caches

---

NewHorizons/Assets/newhorizons_private.manifest
NewHorizons/Builder/Body/SupernovaEffectBuilder.cs
NewHorizons/Builder/General/AmbientLightBuilder.cs
NewHorizons/Components/NHSupernovaPlanetEffectController.cs
NewHorizons/External/Configs/PlanetConfig.cs
NewHorizons/External/Modules/AmbientLightModule.cs
NewHorizons/External/Modules/BaseModule.cs
NewHorizons/Handlers/PlanetCreationHandler.cs
NewHorizons/Schemas/body_schema.json

Ambient light is now a module with additional options for outerRadius, innerRadius, isShell, and tint.

Ambient light module

---

NewHorizons/Assets/newhorizons_private.manifest
NewHorizons/Builder/General/AmbientLightBuilder.cs
NewHorizons/Utility/ImageUtilities.cs

It was unintentionally flipped before.

Fix ambient light cubemap

---

NewHorizons/Builder/Props/DetailBuilder.cs

make the InteractVolume fix and etc use a component instead of FireOnNextUpdate so it works with scatter and VR

Better fixers

---

NewHorizons/Builder/Volumes/CreditsVolumeBuilder.cs
NewHorizons/Components/Volumes/LoadCreditsVolume.cs
NewHorizons/External/Modules/VolumesModule.cs
NewHorizons/Schemas/body_schema.json

- Adds `gameOverText` and `deathType` to credits volumes to display orange text explaining the ending. (#512)

Game over text

---

NewHorizons/External/Configs/StarSystemConfig.cs
NewHorizons/External/Modules/SpawnModule.cs
NewHorizons/Handlers/PlanetCreationHandler.cs
NewHorizons/Handlers/VesselWarpHandler.cs
NewHorizons/Main.cs
NewHorizons/Patches/PlayerPatches/PlayerSpawnerPatches.cs
NewHorizons/Schemas/body_schema.json
NewHorizons/Schemas/star_system_schema.json

- Added `hasZeroGravityVolume` to the Vessel config to remove the default zero-gravity volume around the vessel.
- Added `isDefault` to planet Spawn config to set the default player spawn point, if multiple exist in the system.

Vessel fixes

---

NewHorizons/Builder/Body/RingBuilder.cs
NewHorizons/Components/RingOpacityController.cs

- Fix constant NRE from rings with both a scale curve and opacity curve

Fix ring opacity

---

NewHorizons/Builder/Props/Audio/AudioSourceBuilder.cs
NewHorizons/Builder/Props/Audio/GeneralAudioBuilder.cs
NewHorizons/Builder/Props/Audio/SignalBuilder.cs
NewHorizons/Builder/Props/BrambleNodeBuilder.cs
NewHorizons/Builder/Props/PropBuildManager.cs
NewHorizons/Builder/Volumes/AudioVolumeBuilder.cs
NewHorizons/External/Configs/PlanetConfig.cs
NewHorizons/External/Modules/PropModule.cs
NewHorizons/External/Modules/Props/Audio/AudioSourceInfo.cs
NewHorizons/External/Modules/Props/Audio/BaseAudioInfo.cs
NewHorizons/External/Modules/Props/Audio/SignalInfo.cs
NewHorizons/External/Modules/SignalModule.cs
NewHorizons/Main.cs
NewHorizons/NewHorizonsApi.cs
NewHorizons/OtherMods/AchievementsPlus/AchievementInfo.cs
NewHorizons/Patches/PlayerPatches/PlayerDataPatches.cs
NewHorizons/Patches/SignalPatches/AudioSignalPatches.cs
NewHorizons/Patches/SignalPatches/SignalscopePatches.cs
NewHorizons/Schemas/body_schema.json
NewHorizons/Utility/NewHorizonExtensions.cs
NewHorizons/manifest.json

- Adds `audioSources` as a new `Prop`, allows you to make point audio sources.
- `signals` now have more customization: `minDistance`, `maxDistance` and `volume`.

Added AudioSourceInfo as a new prop, refactors signals

---

NewHorizons/External/NewHorizonsData.cs
NewHorizons/Patches/PlayerPatches/PlayerDataPatches.cs

-
-
-
patch forget frequency so it will work for those using it on custom signals
-

Patch forget frequency

---

NewHorizons/Handlers/VesselWarpHandler.cs
NewHorizons/NewHorizonsApi.cs

- Fixed NullReferenceException when spawning vessels with physics
- Fixed SpawnDialogue API method always creating a remote trigger

Hawkbar minor fixes

---

NewHorizons/Components/AddPhysics.cs

-
-
-
- physics details are now affected by tornadoes
fix #580. i give up on tornadoes

make tornadoes work with physics object

---

NewHorizons/Builder/Body/Geometry/CubeSphere.cs
NewHorizons/Components/AddPhysics.cs
NewHorizons/Main.cs
NewHorizons/Patches/ShapeManagerPatches.cs

-
-
- bump up detector shape limit 4x
- stretch now behaves more intuitively (does not divide min/max height by the largest stretch axis)

Better stretch

---

NewHorizons/Builder/Body/BrambleDimensionBuilder.cs
NewHorizons/Builder/Props/DetailBuilder.cs

resolves #562 
Also fixed an issue where anglerfish weren't animating properly

Fixed "None" vine prefab causing an NRE on dimension enter

---

NewHorizons/External/Modules/BaseModule.cs
NewHorizons/External/Modules/Volumes/VolumeInfos/PriorityVolumeInfo.cs
NewHorizons/Schemas/body_schema.json

-
-
- the documentation for priority volumes is much better now
-

Document layers and priority more

---

NewHorizons/Builder/Atmosphere/AirBuilder.cs
NewHorizons/Builder/Atmosphere/CloudsBuilder.cs
NewHorizons/Builder/Body/WaterBuilder.cs
NewHorizons/Builder/General/GravityBuilder.cs
NewHorizons/External/Modules/VariableSize/WaterModule.cs

-
-
- made gravity/cloud/air/water volumes match base game
-

Fix layers

---

NewHorizons/External/SerializableEnums/NHFluidType.cs
NewHorizons/Schemas/body_schema.json

- added missing fluid types to the enum

add all fluid types

---

NewHorizons/Builder/Body/StarBuilder.cs
NewHorizons/NewHorizons.csproj
NewHorizons/manifest.json
SchemaExporter/SchemaExporter.csproj

-
-
-
- Fix solar system sun solar flares becoming white sometimes (resolves #605)

fix solar flare tinting base game sun

---

NewHorizons/Builder/Props/NomaiTextBuilder.cs
NewHorizons/Builder/Props/TranslatorText/TranslatorTextBuilder.cs
NewHorizons/External/Configs/PlanetConfig.cs
NewHorizons/External/Modules/Props/TranslatorText/NomaiTextType.cs
NewHorizons/Schemas/body_schema.json
SchemaExporter/SchemaExporter.cs

- Added the Ember Twin Cairn variant (#591)
- Renames the cairn NomaiTextType enums to what they actually are.

Add Ember Twin cairn variant

---

NewHorizons/Builder/General/AstroObjectBuilder.cs
NewHorizons/Builder/General/SpawnPointBuilder.cs
NewHorizons/Components/Ship/ShipWarpController.cs
NewHorizons/External/Modules/VariableSize/VariableSizeModule.cs
NewHorizons/Handlers/PlanetCreationHandler.cs
NewHorizons/Handlers/PlayerSpawnHandler.cs
NewHorizons/Handlers/VesselWarpHandler.cs
NewHorizons/Main.cs
NewHorizons/Patches/PlayerPatches/PlayerSpawnerPatches.cs
NewHorizons/Schemas/body_schema.json

- Can now change the spawn point within the base game Hearthian system (resolves #567)
- Fixed spawning on tidally locked planets (resolves #505)

Custom spawn points

---

NewHorizons/Builder/General/AstroObjectBuilder.cs
NewHorizons/Components/Orbital/NHAstroObject.cs
NewHorizons/Handlers/PlanetCreationHandler.cs
NewHorizons/Patches/MapPatches/ReferenceFramePatches.cs

- Fixed vanilla objects being given labels (OPC, QM, SS) #623

Fix QM, OPC, Sun Station debris labeled when locked on #623

---

NewHorizons/Builder/Body/StarBuilder.cs
NewHorizons/Components/SizeControllers/StarEvolutionController.cs

-
-
-
- Fixed solar flare tint not matching star colour #616

Fix solar flare tint

---

NewHorizons/Builder/Props/DetailBuilder.cs
NewHorizons/Main.cs
NewHorizons/NewHorizons.csproj

- Fix softlock affecting The Machine due to a secret hidden slide reel that destroyed everything (thanks Damian)

Machine softlock

---

NewHorizons/Builder/Volumes/VanishVolumeBuilder.cs
NewHorizons/External/Configs/PlanetConfig.cs
NewHorizons/External/Modules/Volumes/ProbeModule.cs
NewHorizons/External/Modules/Volumes/RulesetModule.cs
NewHorizons/External/Modules/Volumes/VolumeInfos/VanishVolumeInfo.cs
NewHorizons/External/Modules/Volumes/VolumesModule.cs
NewHorizons/Schemas/body_schema.json

- Added more to the descriptions of volumes

Add more to the descriptions of volumes

---

NewHorizons/Builder/Body/CloakBuilder.cs
NewHorizons/Builder/General/RFVolumeBuilder.cs
NewHorizons/Components/EOTE/CloakLocatorController.cs
NewHorizons/External/Modules/CloakModule.cs
NewHorizons/Handlers/CloakHandler.cs
NewHorizons/Handlers/PlanetDestructionHandler.cs
NewHorizons/Handlers/VesselCoordinatePromptHandler.cs
NewHorizons/Main.cs

-
-
- 
- More than one cloak can now work at a time, and it only took me over a year #108 
- Stranger cloak will no longer appear in other systems #600
- Fixed cloaks breaking if the planet has no ReferenceFrame enabled

Fix cloaks

---

NewHorizons/Handlers/PlayerSpawnHandler.cs
NewHorizons/Main.cs
NewHorizons/Patches/PlayerPatches/PlayerSpawnerPatches.cs
NewHorizons/Utility/OWML/Delay.cs
NewHorizons/manifest.json

- Fixes dying on spawn in Evacuation

Fix spawn death

---

NewHorizons/Builder/General/AstroObjectBuilder.cs
NewHorizons/Builder/Orbital/InitialMotionBuilder.cs
NewHorizons/Components/PreserveActiveCenterOfTheUniverse.cs
NewHorizons/Handlers/PlanetCreationHandler.cs
NewHorizons/manifest.json

- Fixes dying on spawn in Evacuation
- Fixes the player seeing objects loading out when changing star system
- Fixes a NRE on reload without the Stranger
This time without introducing a bug that breaks systems with only a single planet!

Fix broken patch

---

NewHorizons/External/Configs/StarSystemConfig.cs
NewHorizons/Handlers/PlanetCreationHandler.cs
NewHorizons/Handlers/StarChartHandler.cs
NewHorizons/Main.cs
NewHorizons/NewHorizons.csproj
NewHorizons/Patches/MapPatches/MapControllerPatches.cs
NewHorizons/Patches/PlayerPatches/PlayerStatePatches.cs
NewHorizons/Patches/WarpPatches/ShipCockpitControllerPatches.cs
SchemaExporter/SchemaExporter.csproj

forgot idgaf and am commiting to dev these days

---

NewHorizons/Builder/Props/DetailBuilder.cs
NewHorizons/External/Modules/Props/DetailInfo.cs
NewHorizons/Schemas/body_schema.json

Empty game object

---

NewHorizons/Builder/Body/SingularityBuilder.cs
NewHorizons/Components/Volumes/BlackHoleDestructionVolume.cs
NewHorizons/Components/Volumes/BlackHoleWarpVolume.cs

-
-
- Black hole vanish effects now tied to the size of the black hole. Fixes #215.
- Black hole ambience pitch isn't weirdly high for large black holes anymore. Fixes #226.
- Change system black holes now make a sound when entering them.
-

Black hole fixes

---

NewHorizons/Builder/Volumes/DayNightAudioVolumeBuilder.cs
NewHorizons/Builder/Volumes/VolumesBuildManager.cs
NewHorizons/Components/Volumes/NHDayNightAudioVolume.cs
NewHorizons/External/Modules/Volumes/VolumeInfos/DayNightAudioVolumeInfo.cs
NewHorizons/External/Modules/Volumes/VolumesModule.cs
NewHorizons/Schemas/body_schema.json

- Added new day/night audio volume. Switches between two clips depending on the time of day. Resolves #319 .
-
-
-

Implement day night audio volume

---

NewHorizons/Builder/Props/DetailBuilder.cs

doesnt work on unity objects lol

fix ??= guy

---

NewHorizons/Builder/Props/DialogueBuilder.cs
NewHorizons/Builder/ShipLog/RumorModeBuilder.cs
NewHorizons/External/SerializableData/MColor.cs
NewHorizons/INewHorizons.cs
NewHorizons/Main.cs
NewHorizons/NewHorizonsApi.cs

- New API methods to: Add ship logs from xml, add dialogue from xml, create a new planet from json string. All of these methods work directly with strings or XElements and don't load files on their own.
-
-
-

Ship log api

---

NewHorizons/Patches/AnglerfishAudioControllerPatches.cs

-
-
- Pitch anglerfish sounds based on scale. Resolves #160.
-

Pitch anglerfish sounds based on size

---

NewHorizons/Builder/Body/GeometryBuilder.cs
NewHorizons/Builder/Body/StarBuilder.cs
NewHorizons/Builder/General/RigidBodyBuilder.cs
NewHorizons/Handlers/PlanetCreationHandler.cs
NewHorizons/Handlers/PlanetDestructionHandler.cs

-
-
-
- Shadows glitch out way less
- Custom planets now can have better, longer shadows (using ProxyShadowCaster and ProxyShadowCasterGroup from existing details and in bundles)
- Shadows no longer jitter
- Note: short-distance shadows still cast from planets behind suns. However, this also happens in vanilla, so it is not fixed here

Fix Shadows

---

NewHorizons/Builder/Props/DetailBuilder.cs
NewHorizons/Builder/Props/ShuttleBuilder.cs
NewHorizons/Components/AddPhysics.cs
NewHorizons/Components/Stars/SunLightEffectsController.cs
NewHorizons/External/Modules/Props/DetailInfo.cs
NewHorizons/Schemas/body_schema.json

-
- Add option to freeze a physics detail until its touched. Good for things in zero g
-
-

Make AddPhysics a bit better

---

NewHorizons/Main.cs

- Fix first loop immortality after statue pairing

Possibly fix first loop immortality

---

NewHorizons/Builder/Body/WaterBuilder.cs
NewHorizons/Builder/Orbital/OrbitlineBuilder.cs
NewHorizons/Builder/Props/BrambleNodeBuilder.cs
NewHorizons/Components/SizeControllers/StarEvolutionController.cs
NewHorizons/Components/Stars/SunLightEffectsController.cs
NewHorizons/Components/Volumes/WaterCloakFixerVolume.cs
NewHorizons/External/Modules/OrbitModule.cs
NewHorizons/Handlers/PlanetCreationHandler.cs
NewHorizons/Handlers/PlanetDestructionHandler.cs
NewHorizons/Handlers/PlayerSpawnHandler.cs
NewHorizons/Main.cs
NewHorizons/Patches/ProxyPatches/SunProxyPatches.cs
NewHorizons/Patches/ShipLogPatches/ShipLogEntryLocationPatches.cs
NewHorizons/Patches/SunPatches/SunLightParamUpdaterPatches.cs
NewHorizons/Schemas/body_schema.json

- Fixed spawning inside cloaks. Fixes #671 
- Fixed default system override logging errors on load
- Fixed star size in shader params
- Fixed water inside of cloaks

Cloak fixes

---

NewHorizons/Builder/Props/DetailBuilder.cs
NewHorizons/Patches/WarpPatches/VesselWarpControllerPatches.cs
NewHorizons/manifest.json

Intervention fixes

---

NewHorizons/Handlers/PlanetCreationHandler.cs
NewHorizons/Handlers/PlanetDestructionHandler.cs
NewHorizons/Handlers/ProxyHandler.cs
NewHorizons/Main.cs
NewHorizons/Patches/ProxyPatches/ProxyBodyPatches.cs
NewHorizons/Patches/ProxyPatches/ProxyOrbiterPatches.cs

- Cleaned up how planets are destroyed. Should make load screens faster. Implements #573

Destroy better

---

NewHorizons/Builder/Atmosphere/AirBuilder.cs
NewHorizons/Builder/Atmosphere/EffectsBuilder.cs
NewHorizons/External/Configs/PlanetConfig.cs
NewHorizons/External/Modules/AtmosphereModule.cs
NewHorizons/External/Modules/VectionFieldModule.cs
NewHorizons/Handlers/PlanetCreationHandler.cs
NewHorizons/Schemas/body_schema.json
NewHorizons/Utility/NewHorizonExtensions.cs

- New `ParticleFields` module. Add particles to your planet (ex: leaves, rain, snow, fireflies, and more). Resolves #219 
-
-
-

Particle/Vection Fields

---

NewHorizons/Components/ShipLog/ShipLogStarChartMode.cs
NewHorizons/Handlers/PlanetCreationHandler.cs
NewHorizons/Handlers/PlayerSpawnHandler.cs

- Allow setting ship spawns in main solar system / separately from the player spawn. Implements #677

Ship spawn

---

NewHorizons/Handlers/PlanetCreationHandler.cs
NewHorizons/Handlers/StreamingHandler.cs
NewHorizons/Main.cs
NewHorizons/Streaming/VanillaStreamingFix.cs

- Can now update the orbits of the HGT. Implements #225

Update HGT orbits

---

NewHorizons/Builder/General/DetectorBuilder.cs
NewHorizons/Builder/Props/DetailBuilder.cs
NewHorizons/Builder/Props/GravityCannonBuilder.cs
NewHorizons/NewHorizons.csproj
NewHorizons/Patches/DetectorPatches/PlayerHazardDetectorPatches.cs
NewHorizons/manifest.json

- Log an error when trying to orbit a body that doesn't have a gravity volume.

Fix the what bug again

---

NewHorizons/Schemas/body_schema.json
SchemaExporter/SchemaExporter.cs

Kill Failed Validation Enum Member

---

NewHorizons/Handlers/PlanetDestructionHandler.cs
NewHorizons/Patches/MapPatches/PlaneOffsetMarkerPatches.cs
NewHorizons/manifest.json

- Fix the map grid marker under the player/probe/ship being messed up in other star systems

What if we put the sun back after

---

NewHorizons/Builder/Props/GravityCannonBuilder.cs
NewHorizons/Builder/Props/ShuttleBuilder.cs
NewHorizons/Patches/RigidbodyPatches.cs
NewHorizons/Utility/NewHorizonExtensions.cs
NewHorizons/manifest.json

- Fixes orbs on copied details and rafts not being rotated with planets

Take some rigidbody patches from QSB

---

NewHorizons/Builder/Props/ProjectionBuilder.cs
NewHorizons/External/Modules/Props/EchoesOfTheEye/SlideInfo.cs
NewHorizons/Schemas/body_schema.json

Fix some slide bugs

---

docs/package.json
docs/pnpm-lock.yaml
docs/src/components/Schemas/Content.astro
docs/src/util/schema_utils.ts

Split separate lines of schema descriptions

---

docs/src/components/Schemas/Content.astro

did idiot's thing but properly do line breaks

Split separate lines of schema descriptions but good

---

NewHorizons/Builder/Atmosphere/EffectsBuilder.cs
NewHorizons/Builder/Atmosphere/FogBuilder.cs
NewHorizons/Builder/Props/DetailBuilder.cs
NewHorizons/External/Configs/PlanetConfig.cs
NewHorizons/External/Configs/StarSystemConfig.cs
NewHorizons/Handlers/PlanetCreationHandler.cs
NewHorizons/Utility/Files/AssetBundleUtilities.cs
NewHorizons/Utility/Files/ImageUtilities.cs
NewHorizons/manifest.json

- Fix looping crash of obsolete effects builder method
- Re-added even more missing method signatures that were breaking Dreamstalker (just update your mod xen!)
- Tessellated renderers in asset bundles will now have their shaders replaced just like normal renderers

Dream Of The Stalker

---

NewHorizons/External/Configs/AddonConfig.cs
NewHorizons/Handlers/SubtitlesHandler.cs
NewHorizons/Main.cs
NewHorizons/NewHorizonsApi.cs
NewHorizons/Patches/EyeScenePatches/SubmitActionLoadScenePatches.cs
NewHorizons/Schemas/addon_manifest_schema.json
NewHorizons/Utility/Files/AssetBundleUtilities.cs

- Can now set `preloadBundles` in the addon config file. This will load asset bundles on the main menu and keep them loaded. Will improve initial load times at the cost of more memory usage.
- Can now set `subtitlePath` in the addon config file for displaying a subtitle for your mod on the main menu.

Preloading bundles and setting subtitle path

---

NewHorizons/Builder/Props/DialogueBuilder.cs
NewHorizons/External/Modules/Props/Dialogue/DialogueInfo.cs
NewHorizons/Handlers/TranslationHandler.cs
NewHorizons/Schemas/body_schema.json
NewHorizons/Utility/NewHorizonExtensions.cs

- New `pathToExistingDialogue` field for adding new DialogueNodes and DialogueOptions to existing character dialogues. Just add new responses to Slate's dialogue instead of replacing it! Will improve mod compat and simplify translating.

Dialogue addition

---

NewHorizons/Handlers/TranslationHandler.cs
NewHorizons/Utility/NewHorizonExtensions.cs
NewHorizons/manifest.json

- Translation keys are much more forgiving now (they are case-insensitive and ignore whitespace)

Translation fixes for Astral Codec

---

NewHorizons/Components/TimeLoopController.cs
NewHorizons/Handlers/SystemCreationHandler.cs

- Stops time loop from still happening when the ATP is disabled #796

Dont add timeloopcontroller to base system

---

NewHorizons/Builder/Props/BrambleNodeBuilder.cs
NewHorizons/Components/Volumes/NHInnerFogWarpVolume.cs
NewHorizons/Handlers/SubtitlesHandler.cs
NewHorizons/INewHorizons.cs
NewHorizons/NewHorizonsApi.cs
NewHorizons/Patches/VolumePatches/FogWarpVolumePatches.cs

- Implemented features for potential Outsider compatibility
- NH will not longer resize Dark Brambles fog #778
- Custom Bramble seeds now have fog inside of them

Fixes for Outsider

---

NewHorizons/Builder/ShipLog/MapModeBuilder.cs
NewHorizons/External/Configs/PlanetConfig.cs
NewHorizons/Handlers/SubtitlesHandler.cs

- Fix ship log map mode auto/manual placement
- Fix subtitle becoming invisible when image width is smaller than EOTE subtitle

Hn mapmode and subtitle borked

---

NewHorizons/Patches/BrambleProjectionFixPatches.cs

- Fixes a bug where projecting into Dark Bramble can teleport you (thanks @TRSasasusu for the fix from the Outsider)

Take bramble projection fix from the outsider

---

NewHorizons/Components/Fixers/PlayerShipAtmosphereDetectorFix.cs
NewHorizons/Main.cs

- Fix drowning inside the ship if you spawn inside it (fixes #808)

Fix drowning in ship

---

NewHorizons/Components/Sectored/BrambleSectorController.cs

- Don't explode if an object is deleted in a custom bramble node

Null check under bramble sector controller

---

NewHorizons/Builder/General/RFVolumeBuilder.cs

- Disabled reference frames are no longer targetable (#834)

Fix disabled reference frames

---

NewHorizons/Components/ShipLog/ShipLogStarChartMode.cs
NewHorizons/Handlers/TranslationHandler.cs
NewHorizons/Patches/SignalPatches/AudioSignalPatches.cs
NewHorizons/Utility/DebugTools/DebugReload.cs
NewHorizons/Utility/DebugTools/Menu/DebugMenu.cs
NewHorizons/Utility/NewHorizonExtensions.cs

- Now uses selected language instead of system language when making strings fully uppercase or lowercase in translations

Locale Extensions

---

NewHorizons/External/NewHorizonsData.cs
README.md

- Fix save file bloat from reading popups

Popups read spam

---

NewHorizons/Main.cs
NewHorizons/Patches/RigidbodyPatches.cs
NewHorizons/Utility/NewHorizonExtensions.cs

- fix #865: dont softlock when at the eye (johncorby's fault) 
- fix #783: pause on load like base game does

Fix eye softlock maybe

---

NewHorizons/Builder/General/RFVolumeBuilder.cs

- Fix disabled reference frames not being disabled (I swear I've done this 3 times now)

Fix disabled reference frames not being disabled AGAIN

---

NewHorizons/Builder/General/SectorBuilder.cs

- Fixed sectors being rotated on tidally locked bodies

Fix sectors being rotated on tidally locked bodies

---

NewHorizons/Builder/Body/AsteroidBeltBuilder.cs
NewHorizons/Builder/General/AstroObjectBuilder.cs
NewHorizons/Builder/General/MarkerBuilder.cs
NewHorizons/Components/NHMapMarker.cs
NewHorizons/External/Configs/PlanetConfig.cs
NewHorizons/External/Modules/BaseModule.cs
NewHorizons/External/Modules/MapMarkerModule.cs
NewHorizons/Handlers/PlanetCreationHandler.cs
NewHorizons/Schemas/body_schema.json

- Added a map marker module with display distance overrides (#847)

Add map marker display distance overrides and make a map marker module

---

NewHorizons/Handlers/FadeHandler.cs
NewHorizons/Main.cs
NewHorizons/manifest.json

- Undoes a "fix" that made warping just cut to black instantly

Don't just cut to black on warp

---

NewHorizons/Components/Props/NHSupernovaPlanetEffectController.cs

- Fixed an NRE in NHSupernovaPlanetEffectController that happens with vanilla bodies

Fix NRE in NHSupernovaPlanetEffectController that happens with vanilla bodies

---

NewHorizons/Builder/Props/ProjectionBuilder.cs
NewHorizons/Utility/Files/ImageUtilities.cs
NewHorizons/Utility/Files/SlideReelAsyncImageLoader.cs
NewHorizons/manifest.json

- Slides are now loaded in the background instead of freezing your game. They were supposed to do this before, but clay wrote the code wrong and none of us caught it until now. (Fixes #812)

Actual async slide loading

---

NewHorizons/Builder/Props/Audio/SignalBuilder.cs

- Fix custom signal NRE that happens when going to solar system to get prefabs for eye

Fix custom signal NRE

---

NewHorizons/Builder/Props/PropBuildManager.cs
NewHorizons/Builder/Props/RemoteBuilder.cs
NewHorizons/External/Modules/GeneralPropInfo.cs
NewHorizons/External/Modules/Props/Remote/ProjectionStoneInfo.cs
NewHorizons/External/Modules/Props/Remote/RemoteInfo.cs
NewHorizons/External/Modules/Props/Remote/RemotePlatformInfo.cs
NewHorizons/Handlers/RemoteHandler.cs
NewHorizons/Schemas/body_schema.json
NewHorizons/Schemas/star_system_schema.json
NewHorizons/Utility/NewHorizonExtensions.cs

- Setting `parentPath` will be more robust on most props
Kinda worried about the overhead on this, do we think using `Find` to look for the parent is expensive? We'd be doing it for every prop ever and in most cases it will not matter.

If parent cant be found try creating prop again

---

NewHorizons/Components/EOTE/DreamWorldEndTimes.cs
NewHorizons/External/Configs/StarSystemConfig.cs
NewHorizons/Handlers/StarChartHandler.cs
NewHorizons/Handlers/SystemCreationHandler.cs
NewHorizons/Main.cs
NewHorizons/Patches/GlobalMusicControllerPatches.cs
NewHorizons/Schemas/star_system_schema.json
NewHorizons/Utility/Files/AudioUtilities.cs
NewHorizons/Utility/Files/ImageUtilities.cs
NewHorizons/Utility/NewHorizonExtensions.cs

-  Added `GlobalMusic` module to system config (change end times, bramble dimension, and final end times music) (Resolves #894)
- Fixed global bramble music not playing because all dimensions have an ambient audio volume

Global music module

---

NewHorizons/Handlers/VesselWarpHandler.cs

- No more infinite load when warping back to Outer Wilds system with vessel

No more infinite load when warping back to Outer Wilds system with vessel

---

NewHorizons/Builder/Props/DetailBuilder.cs

- copied dream lanterns now look correct

Fix lantern petals

---

NewHorizons/Builder/Props/WarpPadBuilder.cs

- Fix warp receiver computer not working

Warp receiver computer fix and rename some cloned prefabs in WarpPadBuilder

---

NewHorizons/Builder/Props/ProjectionBuilder.cs
NewHorizons/Main.cs
NewHorizons/Utility/Files/ImageUtilities.cs
NewHorizons/Utility/Files/SlideReelAsyncImageLoader.cs
NewHorizons/default-config.json

- New option setting "sequential pre-caching" will prevent running out of memory when creating slide reel caches

Sequential load slide cache

---

NewHorizons/Handlers/StarChartHandler.cs

Fix that that last update didnt actually work

---

docs/package.json
docs/pnpm-lock.yaml
docs/src/content/docs/guides/troubleshooting.md

Update with any sections you want to add

Add Troubleshooting Page to docs

---

NewHorizons/Builder/Body/BrambleDimensionBuilder.cs
NewHorizons/Builder/Props/TranslatorText/NomaiTextArcBuilder.cs
NewHorizons/Builder/Props/TranslatorText/TranslatorTextBuilder.cs
NewHorizons/External/Modules/BrambleModule.cs
NewHorizons/Schemas/body_schema.json

-
-
-
- Stranger text misalignment (fixed #924)

Even more fixes

---

NewHorizons/Assets/newhorizons_private.manifest

- Fixed simulation materials for custom slide reels. (fixes #946)

Fix slide reel simulation materials

---

NewHorizons/Builder/Props/ProjectionBuilder.cs
NewHorizons/Utility/Files/ImageUtilities.cs
NewHorizons/Utility/Files/SlideReelAsyncImageLoader.cs

- Fixed slide reel caches in multi-system mods

Fix caches in other systems

---

NewHorizons/Builder/Orbital/OrbitlineBuilder.cs
NewHorizons/Handlers/PlanetCreationHandler.cs

- Fixed configs getting loaded more than once if parent body is updated again #921

More fixes

---

NewHorizons/Handlers/HeldItemHandler.cs

- Fix being unable to enter the dream world via dying

Fix held item persistence breaking dream world entry via death

---

NewHorizons/Utility/Files/ImageUtilities.cs

- fix bug where projected slides look too bright

Fix slide colors

---

NewHorizons/Handlers/PlanetCreationHandler.cs
NewHorizons/manifest.json

- Allow spawning inside Bramble dimensions (base game spawn point does not work yet)

Spawn in bramble

---

NewHorizons/Builder/Props/DialogueBuilder.cs
NewHorizons/Schemas/body_schema.json

- Resolve error when specifying a dialogue attention point but not an offset for that attention point

Coalesce to Vector3.zero if attention point offset not specified

---

NewHorizons/Builder/General/SpawnPointBuilder.cs
NewHorizons/manifest.json

- Uncomment that TH spawn fix because somehow it was commented out

Uncomment TH Spawn Flag

---

NewHorizons/Components/Quantum/QuantumPlanet.cs
NewHorizons/External/Configs/PlanetConfig.cs
NewHorizons/Handlers/PlanetCreationHandler.cs
NewHorizons/Schemas/body_schema.json

- Allow planets to choose whether they're factored into changing map zoom speed

Allow planets to choose whether they're factored into changing map zoom speed

---

docs/src/content/docs/start-here/getting-started.md

Nitpick, but just seems a little silly to advertise a schema's `Automatic error detection for incorrect data types or values` right after an example which upsets the LSP.

Update obsolete hasMapMarker in wetrock.json

---

NewHorizons/Builder/Props/QuantumBuilder.cs
NewHorizons/Main.cs
NewHorizons/Utility/Geometry/BoxShapeVisualizer.cs
NewHorizons/default-config.json

- Added option separate from Debug for visualizing quantum object visibility shapes

Add option to toggle quantum object visualization separate from debug

---

NewHorizons/Builder/Body/StellarRemnantBuilder.cs
NewHorizons/Handlers/PlanetCreationHandler.cs

- ID on sector component is now set to the name of the body

Set sector's ID

---

NewHorizons/Builder/General/GravityBuilder.cs
NewHorizons/Builder/Orbital/FocalPointBuilder.cs

- Fix circumbinary planets don't orbit anymore

Fix circumbinary

---

NewHorizons/Handlers/InvulnerabilityHandler.cs
NewHorizons/Handlers/PlayerSpawnHandler.cs
NewHorizons/Handlers/VesselWarpHandler.cs
NewHorizons/Main.cs

- fixes https://github.com/Outer-Wilds-New-Horizons/new-horizons/issues/1034
- might also fix https://github.com/Outer-Wilds-New-Horizons/new-horizons/issues/975 but i couldn't reproduce the issue to be sure.

fix bugs for ship and vessel spawns

---

NewHorizons/Components/Volumes/BlackHoleWarpVolume.cs
NewHorizons/Handlers/FadeHandler.cs

- Screen fades out faster now on system-changing black hole. Fixes #783.

Do the thing where the screen fades out on black holes only

---

NewHorizons/Builder/Props/EyeOfTheUniverseBuilder.cs

- fixes a bug at the eye of the universe where new horizons checks for a condition instead of a persistent condition

fix hawkbar's eye of the universe bug

---

NewHorizons/Builder/General/MarkerBuilder.cs
NewHorizons/Handlers/EyeSceneHandler.cs
NewHorizons/Handlers/TranslationHandler.cs
NewHorizons/Handlers/VesselWarpHandler.cs
NewHorizons/manifest.json

- Fixed broken implementation of #1062 by changing TranslationHandler.AddUI to take a bool for translations being uppercase.

Do the overload with boolean for UI translations being uppercase

---

NewHorizons/Builder/General/SpawnPointBuilder.cs

- NH-made spawn points now show up in Cheat And Debug Menu's spawn point teleporter

Make spawns show up in PlayerSpawner.FindPlanetSpawns

---

docs/src/content/docs/guides/details.md
docs/src/content/docs/guides/troubleshooting.md

update broken unity wiki links, and point to new prop placer mod

Detailing docs

---

NewHorizons/Builder/Props/ProjectionBuilder.cs
NewHorizons/External/Modules/Props/EchoesOfTheEye/ProjectionInfo.cs

- Standing vision torch now shows up in tronworld

Standing Torch Tronworld

---

NewHorizons/Components/NHGameOverManager.cs
NewHorizons/External/Modules/GameOverModule.cs

- Fixed undefined behaviour when custom credits attributes aren't specified

Fixed undefined behaviour when custom credits attributes aren't specified

---

docs/src/content/docs/reference/api.md

- replaced old api with new one in docs

resolve #1060

---

NewHorizons/Builder/ShipLog/MapModeBuilder.cs
NewHorizons/Builder/Volumes/RepairVolumeBuilder.cs
NewHorizons/Builder/Volumes/VolumesBuildManager.cs
NewHorizons/Components/Volumes/NHRepairReceiver.cs
NewHorizons/External/Modules/Volumes/VolumeInfos/RepairVolumeInfo.cs
NewHorizons/External/Modules/Volumes/VolumesModule.cs
NewHorizons/Handlers/PlanetCreationHandler.cs
NewHorizons/Patches/VolumePatches/RepairReceiverPatches.cs
NewHorizons/Schemas/body_schema.json

- Added `repairVolumes` which act like the repairable nodes on the "satellite" in the Zero-G cave. Resolves #1084
[Examples PR](https://github.com/Outer-Wilds-New-Horizons/nh-examples/pull/59)
Also in this PR I've fixed two unrelated minor issues that were causing warnings to be flagged on every build.

Repair Volumes

---

NewHorizons/Builder/Props/ItemBuilder.cs

- Fix custom items not having sound when you make socket with the same custom type first

Fix items not having sound when you make socket first

---

docs/src/content/docs/guides/nomai-text.md
docs/src/content/docs/start-here/helpful-resources.md

- Added Nomai Text Printer to the docs, since it can be useful

Add Nomai Text Printer to the docs

---

CONTRIBUTING.md
NewHorizons/External/Modules/VariableSize/VariableSizeModule.cs

Reasoning: it was unclear that the scale of the in-game object will still be affected by the size value of the object and not outright overridden by the value value.

Edit documentation of VariableSizeModule
